import { randomUUID } from 'node:crypto';
import { and, desc, eq, inArray } from 'drizzle-orm';
import { contentHash, normalizeDomain } from '@gtm/shared';
import type { ContactDraft, ContactValidationResult, EmailPattern, PersonDraft, RankedPerson } from '@gtm/contacts';
import type { DatabaseConnection } from './client.js';
import { activities, companies, companyProfiles, contactResearchRuns, contacts, contactSources, contactValidations, decisionMakerSelections, dnsCache, emailPatterns, people, personEvidence, personSources, workerJobs } from './schema.js';

const activeStates = ['QUEUED','DISCOVERING_PEOPLE','RANKING','DISCOVERING_CONTACTS','DETECTING_PATTERN','VALIDATING'];
export class ContactRepository {
  constructor(private readonly connection: DatabaseConnection) {}
  private get db() { return this.connection.db; }

  queue(companyId: string, options: { manual?: boolean; force?: boolean; minClientScore?: number; ttlDays?: number } = {}) {
    const company = this.db.select().from(companies).where(eq(companies.id, companyId)).get(); if (!company) throw new Error('Company not found');
    const clientScore = (this.connection.sqlite.prepare('SELECT MAX(current_score) score FROM client_opportunities WHERE company_id=?').get(companyId) as { score: number | null }).score ?? 0;
    if (!options.manual && clientScore < (options.minClientScore ?? 75)) return { queued: false, reason: 'NOT_ELIGIBLE' as const, runId: null };
    const latest = this.db.select().from(contactResearchRuns).where(eq(contactResearchRuns.companyId, companyId)).orderBy(desc(contactResearchRuns.createdAt)).get();
    if (!options.force && latest?.status === 'COMPLETE' && latest.completedAt && latest.completedAt > addDays(iso(), -(options.ttlDays ?? 14))) { const changed=this.connection.sqlite.prepare(`SELECT EXISTS(SELECT 1 FROM jobs WHERE company_id=? AND first_discovered_at>?) OR EXISTS(SELECT 1 FROM company_profiles WHERE id=? AND created_at>?) changed`).get(companyId,latest.completedAt,company.currentProfileId,latest.completedAt) as {changed:number}; if(!changed.changed)return { queued: false, reason: 'FRESH' as const, runId: latest.id }; }
    const active = this.db.select().from(contactResearchRuns).where(and(eq(contactResearchRuns.companyId, companyId), inArray(contactResearchRuns.status, activeStates))).get();
    if (active) return { queued: false, reason: 'ALREADY_QUEUED' as const, runId: active.id };
    const now=iso(), runId=randomUUID(), priority=options.manual ? 100 : clientScore;
    this.db.transaction((tx) => { tx.insert(contactResearchRuns).values({ id:runId, companyId, status:'QUEUED', trigger:options.manual?'MANUAL':'ELIGIBILITY', priority, forceRefresh:options.force??false, createdAt:now, updatedAt:now }).run(); tx.insert(workerJobs).values({ id:randomUUID(), type:'DISCOVER_COMPANY_PEOPLE', payloadJson:JSON.stringify({companyId,contactResearchRunId:runId}), status:'PENDING', priority, attempts:0, maxAttempts:3, runAfter:now, idempotencyKey:`contacts:${runId}:people`, createdAt:now }).run(); tx.insert(activities).values({ id:randomUUID(), entityType:'COMPANY', entityId:companyId, type:'CONTACT_INTELLIGENCE_QUEUED', actor:options.manual?'USER':'SYSTEM', toStatus:'QUEUED', metadataJson:JSON.stringify({contactResearchRunId:runId,priority}), occurredAt:now, createdAt:now }).run(); });
    return { queued:true, reason:null, runId };
  }
  getRun(id:string) { return this.db.select().from(contactResearchRuns).where(eq(contactResearchRuns.id,id)).get() ?? null; }
  setStatus(id:string,status:string,patch:Partial<typeof contactResearchRuns.$inferInsert>={}) { const run=this.getRun(id); if(!run) throw new Error('Contact research run not found'); const now=iso(); this.db.update(contactResearchRuns).set({status,updatedAt:now,...(!run.startedAt?{startedAt:now}:{}),...patch}).where(eq(contactResearchRuns.id,id)).run(); }
  fail(id:string,error:unknown) { this.setStatus(id,'FAILED',{completedAt:iso(),errorJson:JSON.stringify(serializeError(error))}); }
  getCompanyContext(companyId:string) { const company=this.db.select().from(companies).where(eq(companies.id,companyId)).get(); if(!company) throw new Error('Company not found'); const profile=company.currentProfileId?this.db.select().from(companyProfiles).where(eq(companyProfiles.id,company.currentProfileId)).get():null; return {company,profile:profile?{businessModel:profile.businessModel,stage:profile.stage,technicalFocus:parseStrings(profile.technicalFocusJson),recommendedServices:parseStrings(profile.servicesJson)}:null}; }
  getCurrentPages(companyId:string) { const rows=this.connection.sqlite.prepare(`SELECT p.id pageId,p.url,p.page_type pageType,v.text_content textContent,v.headings_json headingsJson,v.links_json linksJson,v.emails_json emailsJson,v.social_urls_json socialUrlsJson,v.structured_data_json structuredDataJson FROM company_pages p JOIN company_page_versions v ON v.id=p.current_version_id WHERE p.company_id=? AND v.error_json IS NULL ORDER BY CASE p.page_type WHEN 'TEAM' THEN 0 WHEN 'ABOUT' THEN 1 WHEN 'NEWS' THEN 2 ELSE 3 END,p.last_fetched_at DESC`).all(companyId) as Record<string,unknown>[]; return rows.map((row)=>({pageId:String(row.pageId),url:String(row.url),pageType:String(row.pageType),textContent:String(row.textContent??''),headings:parseArray(row.headingsJson),links:parseArray(row.linksJson),emails:parseArray(row.emailsJson),socialUrls:parseArray(row.socialUrlsJson),structuredData:parseArray(row.structuredDataJson)})); }

  savePeople(runId:string,drafts:PersonDraft[]) { const run=this.requireRun(runId), now=iso(); const unique=new Map(drafts.map((item)=>[item.normalizedName,item])); this.db.transaction((tx)=>{ for(const item of unique.values()){ let person=tx.select().from(people).where(and(eq(people.companyId,run.companyId),eq(people.normalizedName,item.normalizedName))).get(); if(!person){ const id=randomUUID(); tx.insert(people).values({id,companyId:run.companyId,fullName:item.fullName,normalizedName:item.normalizedName,firstName:item.firstName,lastName:item.lastName,title:item.title,normalizedTitle:item.normalizedTitle,department:item.department,seniority:item.seniority,confidence:item.confidence,linkedinUrl:item.linkedinUrl,githubUrl:item.githubUrl,firstDiscoveredAt:now,lastVerifiedAt:now,createdAt:now,updatedAt:now}).run(); person=tx.select().from(people).where(eq(people.id,id)).get()!; } else tx.update(people).set({title:item.title,normalizedTitle:item.normalizedTitle,department:item.department,seniority:item.seniority,confidence:Math.max(person.confidence,item.confidence),linkedinUrl:item.linkedinUrl??person.linkedinUrl,githubUrl:item.githubUrl??person.githubUrl,lastVerifiedAt:now,updatedAt:now}).where(eq(people.id,person.id)).run();
      const hash=contentHash([item.normalizedName,item.normalizedTitle,item.sourceUrl,item.evidenceText]); tx.insert(personSources).values({id:randomUUID(),personId:person.id,contactResearchRunId:runId,pageId:item.pageId,sourceUrl:item.sourceUrl,sourceType:item.sourceType,contentHash:hash,firstSeenAt:now,lastSeenAt:now,createdAt:now}).onConflictDoNothing().run(); tx.insert(personEvidence).values({id:randomUUID(),personId:person.id,contactResearchRunId:runId,pageId:item.pageId,claim:`${item.fullName} is ${item.title}`,evidenceText:item.evidenceText,sourceUrl:item.sourceUrl,sourceQuality:'FIRST_PARTY_HIGH',confidence:item.confidence,contentHash:hash,createdAt:now}).onConflictDoNothing().run(); }
      tx.update(contactResearchRuns).set({peopleFound:unique.size,updatedAt:now}).where(eq(contactResearchRuns.id,runId)).run(); }); return unique.size; }
  getPersonDrafts(companyId:string):Array<PersonDraft & {id:string}> { return this.db.select().from(people).where(eq(people.companyId,companyId)).all().map((p)=>({id:p.id,fullName:p.fullName,firstName:p.firstName,lastName:p.lastName,normalizedName:p.normalizedName,title:p.title,normalizedTitle:p.normalizedTitle,department:p.department as PersonDraft['department'],seniority:p.seniority as PersonDraft['seniority'],sourceUrl:'',sourceType:'',evidenceText:'',confidence:p.confidence,linkedinUrl:p.linkedinUrl,githubUrl:p.githubUrl})); }
  saveRanking(runId:string,ranked:Array<RankedPerson & {id:string}>) { const run=this.requireRun(runId),now=iso(); this.db.transaction((tx)=>{ for(const item of ranked) tx.update(people).set({decisionMakerScore:item.score,decisionMakerReason:item.reason,confidence:item.confidence,updatedAt:now}).where(eq(people.id,item.id)).run(); if(ranked[0]){ tx.update(decisionMakerSelections).set({active:false}).where(and(eq(decisionMakerSelections.companyId,run.companyId),eq(decisionMakerSelections.active,true))).run(); tx.insert(decisionMakerSelections).values({id:randomUUID(),companyId:run.companyId,contactResearchRunId:runId,primaryPersonId:ranked[0].id,secondaryPersonId:ranked[1]?.id,score:ranked[0].score,reason:ranked[0].reason,confidence:ranked[0].confidence,selectedBy:'SYSTEM',active:true,createdAt:now}).run(); } }); return ranked.length; }
  manualSelect(companyId:string,primaryPersonId:string,secondaryPersonId?:string|null) { const candidates=this.db.select().from(people).where(eq(people.companyId,companyId)).all(); const primary=candidates.find((p)=>p.id===primaryPersonId); if(!primary || (secondaryPersonId&&!candidates.some((p)=>p.id===secondaryPersonId))) throw new Error('Person not found for company'); const now=iso(); this.db.transaction((tx)=>{tx.update(decisionMakerSelections).set({active:false}).where(and(eq(decisionMakerSelections.companyId,companyId),eq(decisionMakerSelections.active,true))).run();tx.insert(decisionMakerSelections).values({id:randomUUID(),companyId,primaryPersonId,secondaryPersonId:secondaryPersonId??null,score:primary.decisionMakerScore,reason:'Manually selected decision maker',confidence:primary.confidence,selectedBy:'USER',active:true,createdAt:now}).run();tx.insert(activities).values({id:randomUUID(),entityType:'COMPANY',entityId:companyId,type:'DECISION_MAKER_SELECTED',actor:'USER',metadataJson:JSON.stringify({primaryPersonId,secondaryPersonId}),occurredAt:now,createdAt:now}).run();}); }

  saveContacts(runId:string,drafts:ContactDraft[]) { const run=this.requireRun(runId),peopleRows=this.db.select().from(people).where(eq(people.companyId,run.companyId)).all(),now=iso(); let count=0; this.db.transaction((tx)=>{for(const item of drafts){const person=peopleRows.find((p)=>p.normalizedName===item.personNormalizedName);let contact=tx.select().from(contacts).where(and(eq(contacts.companyId,run.companyId),eq(contacts.normalizedValue,item.value.toLowerCase()))).get();if(!contact){const id=randomUUID();tx.insert(contacts).values({id,companyId:run.companyId,personId:person?.id,type:'EMAIL',contactValue:item.value,normalizedValue:item.value.toLowerCase(),status:item.status,confidence:item.confidence,patternUsed:item.patternUsed,firstDiscoveredAt:now,lastCheckedAt:now,createdAt:now,updatedAt:now}).run();contact=tx.select().from(contacts).where(eq(contacts.id,id)).get()!;}else tx.update(contacts).set({personId:person?.id??contact.personId,status:item.status==='PUBLIC_NAMED'?'PUBLIC_NAMED':contact.status,confidence:Math.max(contact.confidence,item.confidence),lastCheckedAt:now,updatedAt:now}).where(eq(contacts.id,contact.id)).run();const hash=contentHash([item.value,item.sourceUrl,item.status]);tx.insert(contactSources).values({id:randomUUID(),contactId:contact.id,contactResearchRunId:runId,pageId:item.pageId,sourceUrl:item.sourceUrl,sourceType:item.sourceType,contentHash:hash,firstSeenAt:now,lastSeenAt:now,createdAt:now}).onConflictDoNothing().run();count+=1;}tx.update(contactResearchRuns).set({contactsFound:count,updatedAt:now}).where(eq(contactResearchRuns.id,runId)).run();});return count; }
  savePattern(runId:string,pattern:EmailPattern) { const run=this.requireRun(runId),now=iso(); this.db.insert(emailPatterns).values({id:randomUUID(),companyId:run.companyId,contactResearchRunId:runId,domain:pattern.domain,pattern:pattern.pattern,evidenceEmailsJson:JSON.stringify(pattern.evidenceEmails),confidence:pattern.confidence,createdAt:now}).onConflictDoNothing().run(); }
  getNamedForPattern(companyId:string) { return this.connection.sqlite.prepare(`SELECT c.contact_value email,p.first_name firstName,p.last_name lastName,p.normalized_name normalizedName FROM contacts c JOIN people p ON p.id=c.person_id WHERE c.company_id=? AND c.status='PUBLIC_NAMED'`).all(companyId) as Array<{email:string;firstName:string;lastName:string;normalizedName:string}>; }
  getUncontactedDecisionMakers(companyId:string) { return this.connection.sqlite.prepare(`SELECT p.* FROM people p LEFT JOIN contacts c ON c.person_id=p.id WHERE p.company_id=? AND c.id IS NULL AND p.decision_maker_score>=35 ORDER BY p.decision_maker_score DESC LIMIT 5`).all(companyId) as Array<typeof people.$inferSelect>; }
  getContactsForRun(runId:string) { return this.connection.sqlite.prepare(`SELECT DISTINCT c.* FROM contacts c JOIN contact_sources cs ON cs.contact_id=c.id WHERE cs.contact_research_run_id=?`).all(runId) as Array<typeof contacts.$inferSelect>; }
  getContact(id:string) { return this.db.select().from(contacts).where(eq(contacts.id,id)).get()??null; }
  getLatestPattern(companyId:string) { const row=this.db.select().from(emailPatterns).where(eq(emailPatterns.companyId,companyId)).orderBy(desc(emailPatterns.createdAt)).get(); return row?{pattern:row.pattern,domain:row.domain,evidenceEmails:parseArray(row.evidenceEmailsJson) as string[],confidence:row.confidence}:null; }
  saveValidation(contactId:string,result:ContactValidationResult,ttlDays:number,confidence:number) { const now=iso();this.db.transaction((tx)=>{tx.insert(contactValidations).values({id:randomUUID(),contactId,syntaxValid:result.syntaxValid,domainMatches:result.domainMatches,disposable:result.disposable,dnsStatus:result.dnsStatus,mxStatus:result.mxStatus,mxHostsJson:JSON.stringify(result.mxHosts),checkedAt:now,expiresAt:addDays(now,ttlDays),errorJson:result.error?JSON.stringify({message:result.error}):null,createdAt:now}).run();tx.update(contacts).set({confidence,lastCheckedAt:now,updatedAt:now}).where(eq(contacts.id,contactId)).run();}); }
  getFreshValidation(contactId:string) { return this.db.select().from(contactValidations).where(and(eq(contactValidations.contactId,contactId))).orderBy(desc(contactValidations.checkedAt)).all().find((item)=>item.expiresAt>iso())??null; }
  getFreshDns(domain:string){const row=this.db.select().from(dnsCache).where(eq(dnsCache.domain,normalizeDomain(domain)??domain)).get();return row&&row.expiresAt>iso()?{dnsStatus:row.dnsStatus as ContactValidationResult['dnsStatus'],mxStatus:row.mxStatus as ContactValidationResult['mxStatus'],mxHosts:parseArray(row.mxHostsJson) as string[],error:row.errorJson??undefined}:null;}
  saveDns(domain:string,result:ContactValidationResult,ttlDays:number){const normalized=normalizeDomain(domain);if(!normalized)return;const now=iso();this.db.insert(dnsCache).values({domain:normalized,dnsStatus:result.dnsStatus,mxStatus:result.mxStatus,mxHostsJson:JSON.stringify(result.mxHosts),checkedAt:now,expiresAt:addDays(now,ttlDays),errorJson:result.error?JSON.stringify({message:result.error}):null,updatedAt:now}).onConflictDoUpdate({target:dnsCache.domain,set:{dnsStatus:result.dnsStatus,mxStatus:result.mxStatus,mxHostsJson:JSON.stringify(result.mxHosts),checkedAt:now,expiresAt:addDays(now,ttlDays),errorJson:result.error?JSON.stringify({message:result.error}):null,updatedAt:now}}).run();}
  validationJobSummary(runId:string){return this.connection.sqlite.prepare(`SELECT SUM(CASE WHEN status IN ('PENDING','RETRY','RUNNING') THEN 1 ELSE 0 END) remaining,SUM(CASE WHEN status='FAILED' THEN 1 ELSE 0 END) failed FROM worker_jobs WHERE type='VALIDATE_CONTACT' AND json_extract(payload_json,'$.contactResearchRunId')=?`).get(runId) as {remaining:number|null;failed:number|null};}
  finalize(runId:string,status:'COMPLETE'|'PARTIAL'='COMPLETE') { const run=this.requireRun(runId),now=iso();this.setStatus(runId,status,{completedAt:now});this.db.insert(activities).values({id:randomUUID(),entityType:'COMPANY',entityId:run.companyId,type:'CONTACT_INTELLIGENCE_COMPLETED',actor:'SYSTEM',metadataJson:JSON.stringify({contactResearchRunId:runId,status}),occurredAt:now,createdAt:now}).run(); }
  getCompanyIntelligence(companyId:string) { const personRows=this.connection.sqlite.prepare(`SELECT p.*,e.source_url sourceUrl,e.evidence_text evidenceText FROM people p LEFT JOIN person_evidence e ON e.id=(SELECT x.id FROM person_evidence x WHERE x.person_id=p.id ORDER BY x.created_at DESC LIMIT 1) WHERE p.company_id=? ORDER BY p.decision_maker_score DESC`).all(companyId) as Record<string,unknown>[];const mappedPeople=personRows.map((p)=>({id:p.id,companyId:p.company_id,fullName:p.full_name,normalizedName:p.normalized_name,firstName:p.first_name,lastName:p.last_name,title:p.title,normalizedTitle:p.normalized_title,department:p.department,seniority:p.seniority,decisionMakerScore:p.decision_maker_score,decisionMakerReason:p.decision_maker_reason,confidence:p.confidence,linkedinUrl:p.linkedin_url,githubUrl:p.github_url,lastVerifiedAt:p.last_verified_at,sourceUrl:p.sourceUrl,evidenceText:p.evidenceText}));const contactRows=this.connection.sqlite.prepare(`SELECT c.id,c.person_id personId,c.contact_value contactValue,c.status,c.confidence,c.pattern_used patternUsed,c.last_checked_at lastCheckedAt,v.syntax_valid syntaxValid,v.domain_matches domainMatches,v.disposable,v.dns_status dnsStatus,v.mx_status mxStatus,v.mx_hosts_json mxHostsJson,cs.source_url sourceUrl FROM contacts c LEFT JOIN contact_validations v ON v.id=(SELECT x.id FROM contact_validations x WHERE x.contact_id=c.id ORDER BY x.checked_at DESC LIMIT 1) LEFT JOIN contact_sources cs ON cs.id=(SELECT y.id FROM contact_sources y WHERE y.contact_id=c.id ORDER BY y.last_seen_at DESC LIMIT 1) WHERE c.company_id=? ORDER BY c.confidence DESC`).all(companyId) as Record<string,unknown>[];const selection=this.connection.sqlite.prepare(`SELECT d.id,d.primary_person_id primaryPersonId,d.secondary_person_id secondaryPersonId,d.score,d.reason,d.confidence,d.selected_by selectedBy,d.created_at createdAt,p.full_name primaryName,p.title primaryTitle,s.full_name secondaryName,s.title secondaryTitle FROM decision_maker_selections d JOIN people p ON p.id=d.primary_person_id LEFT JOIN people s ON s.id=d.secondary_person_id WHERE d.company_id=? AND d.active=1 ORDER BY d.created_at DESC LIMIT 1`).get(companyId)??null;const runs=this.db.select().from(contactResearchRuns).where(eq(contactResearchRuns.companyId,companyId)).orderBy(desc(contactResearchRuns.createdAt)).all();return {people:mappedPeople,contacts:contactRows.map((row)=>({...row,mxHosts:parseArray(row.mxHostsJson)})),decisionMaker:selection,runs}; }
  getPersonEvidence(personId:string) { return this.db.select().from(personEvidence).where(eq(personEvidence.personId,personId)).orderBy(desc(personEvidence.createdAt)).all(); }
  private requireRun(id:string) { const run=this.getRun(id);if(!run)throw new Error('Contact research run not found');return run; }
}
function parseArray(value:unknown):unknown[]{try{return JSON.parse(String(value??'[]')) as unknown[];}catch{return[];}}
function parseStrings(value:unknown):string[]{return parseArray(value).filter((item):item is string=>typeof item==='string');}
function iso(){return new Date().toISOString();} function addDays(value:string,days:number){return new Date(new Date(value).getTime()+days*86_400_000).toISOString();}
function serializeError(error:unknown){return error instanceof Error?{name:error.name,message:error.message,stack:error.stack}:{message:String(error)};}
