import fs from 'node:fs';import path from 'node:path';import {randomUUID}from'node:crypto';
import {and,desc,eq,lte}from'drizzle-orm';
import {cohortAnalysis,evaluateProbability,modelEligibility,predictProbability,trainLogisticRegression,type TrainingRow}from'@gtm/analytics';
import {threadMatch}from'@gtm/operations';
import type{DatabaseConnection}from'./client.js';
import{backupHistory,campaigns,inboundCheckpoints,learningRecommendations,modelSnapshots,schedulerLeases,workerJobs}from'./schema.js';

export class FinalRepository{
 constructor(private readonly connection:DatabaseConnection){}
 private get db(){return this.connection.db;}
 listCampaigns(){return this.connection.sqlite.prepare(`SELECT c.*,s.name serviceName,(SELECT COUNT(*) FROM campaign_members m WHERE m.campaign_id=c.id) members,(SELECT COUNT(DISTINCT opportunity_id) FROM conversion_events e WHERE e.campaign_id=c.id AND e.stage='CLIENT_CONTACTED') contacted,(SELECT COUNT(DISTINCT opportunity_id) FROM conversion_events e WHERE e.campaign_id=c.id AND e.stage='CLIENT_POSITIVE_REPLY') positiveReplies,(SELECT COUNT(DISTINCT opportunity_id) FROM conversion_events e WHERE e.campaign_id=c.id AND e.stage='CLIENT_WON') wins,(SELECT COALESCE(SUM(revenue_cents),0) FROM conversion_events e WHERE e.campaign_id=c.id AND e.stage='CLIENT_WON') revenueCents FROM campaigns c LEFT JOIN services s ON s.id=c.primary_service_id ORDER BY c.created_at DESC`).all();}
 createCampaign(input:{name:string;primaryServiceId?:string;targeting:Record<string,unknown>;messageStrategy?:string}){const now=iso(),id=randomUUID();this.db.insert(campaigns).values({id,name:input.name,primaryServiceId:input.primaryServiceId,targetingJson:JSON.stringify(input.targeting),messageStrategy:input.messageStrategy,status:'DRAFT',createdAt:now,updatedAt:now}).run();return this.getCampaign(id);}
 updateCampaign(id:string,input:{name?:string;primaryServiceId?:string|null;targeting?:Record<string,unknown>;messageStrategy?:string|null;status?:'DRAFT'|'ACTIVE'|'PAUSED'|'ARCHIVED'}){const row=this.getCampaign(id);if(!row)throw new Error('Campaign not found');this.db.update(campaigns).set({...input,...(input.targeting?{targetingJson:JSON.stringify(input.targeting)}:{}),updatedAt:iso()}).where(eq(campaigns.id,id)).run();return this.getCampaign(id);}
 getCampaign(id:string){return this.db.select().from(campaigns).where(eq(campaigns.id,id)).get()??null;}

 getCheckpoint(provider='IMAP',mailbox='INBOX'){return this.db.select().from(inboundCheckpoints).where(and(eq(inboundCheckpoints.provider,provider),eq(inboundCheckpoints.mailbox,mailbox))).get()??{provider,mailbox,lastUid:0,uidValidity:null};}
 saveCheckpoint(provider:string,mailbox:string,lastUid:number,uidValidity?:string){const now=iso(),current=this.db.select().from(inboundCheckpoints).where(and(eq(inboundCheckpoints.provider,provider),eq(inboundCheckpoints.mailbox,mailbox))).get();if(current)this.db.update(inboundCheckpoints).set({lastUid:Math.max(current.lastUid,lastUid),uidValidity:uidValidity??current.uidValidity,updatedAt:now}).where(eq(inboundCheckpoints.id,current.id)).run();else this.db.insert(inboundCheckpoints).values({id:randomUUID(),provider,mailbox,lastUid,uidValidity,updatedAt:now}).run();}
 matchInbound(input:{inReplyTo?:string;references:string[];sender:string;subject:string}){const rows=this.connection.sqlite.prepare(`SELECT t.id,t.normalized_subject normalizedSubject,c.normalized_value contact,GROUP_CONCAT(m.message_id) messageIds FROM email_threads t LEFT JOIN contacts c ON c.id=t.contact_id LEFT JOIN email_messages m ON m.thread_id=t.id WHERE t.status='OPEN' GROUP BY t.id ORDER BY t.last_message_at DESC LIMIT 500`).all()as Array<{id:string;normalizedSubject:string;contact:string|null;messageIds:string|null}>;return threadMatch(input,rows.map(row=>({...row,messageIds:(row.messageIds??'').split(',').filter(Boolean)})))??null;}
 schedule(type:string,payload:Record<string,unknown>,key:string,runAfter:string,priority=50){const now=iso();this.db.insert(workerJobs).values({id:randomUUID(),type,payloadJson:JSON.stringify(payload),status:'PENDING',priority,attempts:0,maxAttempts:3,runAfter,idempotencyKey:key,createdAt:now}).onConflictDoNothing().run();}
 scheduleRecurring(options:{imapEnabled?:boolean}={},now=new Date()){const definitions=[...(options.imapEnabled?[['POLL_INBOX',5*60_000]as const]:[]),['PROCESS_FOLLOWUP',15*60_000]as const,['CALCULATE_ANALYTICS',86_400_000]as const,['EVALUATE_MODELS',7*86_400_000]as const];for(const[type,interval]of definitions){const lease=this.db.select().from(schedulerLeases).where(eq(schedulerLeases.key,type)).get();if(!lease){this.db.insert(schedulerLeases).values({key:type,nextRunAt:now.toISOString(),updatedAt:now.toISOString()}).run();}const current=this.db.select().from(schedulerLeases).where(eq(schedulerLeases.key,type)).get()!;if(current.nextRunAt<=now.toISOString()){this.schedule(type,{},`${type}:${current.nextRunAt}`,now.toISOString(),type==='POLL_INBOX'?90:40);this.db.update(schedulerLeases).set({lastRunAt:now.toISOString(),nextRunAt:new Date(now.getTime()+interval).toISOString(),updatedAt:now.toISOString()}).where(eq(schedulerLeases.key,type)).run();}}}
 schedulerHealth(){return{leases:this.db.select().from(schedulerLeases).all(),overdue:this.db.select().from(schedulerLeases).where(lte(schedulerLeases.nextRunAt,new Date(Date.now()-600_000).toISOString())).all().length};}

 analytics(from?:string,to?:string){const start=from??'1970-01-01T00:00:00.000Z',end=to??iso();const eventRows=this.connection.sqlite.prepare(`SELECT funnel,opportunity_id opportunityId,stage,source_id sourceId,campaign_id campaignId,revenue_cents revenueCents,metadata_json metadataJson,occurred_at occurredAt FROM conversion_events WHERE occurred_at BETWEEN ? AND ?`).all(start,end)as Array<Record<string,unknown>>;const clientStages=['CLIENT_CONTACTED','CLIENT_DELIVERED','CLIENT_REPLIED','CLIENT_POSITIVE_REPLY','CLIENT_MEETING','CLIENT_PROPOSAL','CLIENT_WON','CLIENT_LOST'],jobStages=['JOB_APPLIED','JOB_REPLY','JOB_SCREENING','JOB_INTERVIEW','JOB_TECHNICAL_INTERVIEW','JOB_FINAL_INTERVIEW','JOB_OFFER','JOB_ACCEPTED','JOB_REJECTED'];const counts=(funnel:string,stages:string[]):Record<string,number>=>Object.fromEntries(stages.map(stage=>[stage,eventRows.filter(row=>row.funnel===funnel&&row.stage===stage).length]));const clientDiscovered=(this.connection.sqlite.prepare(`SELECT COUNT(*) count FROM client_opportunities WHERE discovered_at BETWEEN ? AND ?`).get(start,end)as{count:number}).count,jobDiscovered=(this.connection.sqlite.prepare(`SELECT COUNT(*) count FROM job_opportunities WHERE discovered_at BETWEEN ? AND ?`).get(start,end)as{count:number}).count;const client:Record<string,number>={discovered:clientDiscovered,qualified:(this.connection.sqlite.prepare(`SELECT COUNT(*) count FROM client_opportunities WHERE current_score>=70 AND discovered_at BETWEEN ? AND ?`).get(start,end)as{count:number}).count,...counts('CLIENT',clientStages)},job:Record<string,number>={discovered:jobDiscovered,qualified:(this.connection.sqlite.prepare(`SELECT COUNT(*) count FROM job_opportunities WHERE current_score>=70 AND discovered_at BETWEEN ? AND ?`).get(start,end)as{count:number}).count,...counts('JOB',jobStages)};const revenue=this.connection.sqlite.prepare(`SELECT COALESCE(SUM(value_cents),0) totalWonRevenue,COUNT(*) wonDeals,COALESCE(AVG(value_cents),0) averageDealValue FROM deals WHERE status='WON' AND won_at BETWEEN ? AND ?`).get(start,end)as Record<string,number>;const total=revenue.totalWonRevenue??0,contacted=client.CLIENT_CONTACTED??0;return{window:{from:start,to:end},client:{...client,rates:rates(clientDiscovered,client)},job:{...job,rates:rates(jobDiscovered,job)},revenue:{...revenue,revenuePerLead:clientDiscovered?total/clientDiscovered:null,revenuePerContacted:contacted?total/contacted:null},sources:this.sourceRankings(start,end),cohorts:this.cohorts(start,end),insights:this.insights(start,end)};}
 sourceRankings(start='1970-01-01',end=iso()){return this.connection.sqlite.prepare(`SELECT s.id,s.name,s.kind,COUNT(DISTINCT co.id) discovered,COUNT(DISTINCT CASE WHEN co.current_score>=70 THEN co.id END) qualified,COUNT(DISTINCT CASE WHEN ce.stage='CLIENT_POSITIVE_REPLY' THEN ce.opportunity_id END) positiveReplies,COUNT(DISTINCT CASE WHEN ce.stage='CLIENT_MEETING' THEN ce.opportunity_id END) meetings,COUNT(DISTINCT CASE WHEN ce.stage='CLIENT_WON' THEN ce.opportunity_id END) wins,COALESCE(SUM(CASE WHEN ce.stage='CLIENT_WON' THEN ce.revenue_cents END),0) revenueCents FROM sources s LEFT JOIN job_sources js ON js.source_id=s.id LEFT JOIN jobs j ON j.id=js.job_id LEFT JOIN client_opportunities co ON co.trigger_job_id=j.id LEFT JOIN conversion_events ce ON ce.opportunity_id=co.id AND ce.occurred_at BETWEEN ? AND ? GROUP BY s.id ORDER BY revenueCents DESC,meetings DESC,positiveReplies DESC,qualified DESC`).all(start,end);}
 cohorts(start:string,end:string){const rows=this.connection.sqlite.prepare(`SELECT co.id,COALESCE(c.industry,'Unknown') industry,COALESCE(cp.stage,'Unknown') stage,COALESCE(p.normalized_title,'Unknown') role,COALESCE(ct.status,'UNKNOWN') contactType,COALESCE(sv.name,'Unknown') service,EXISTS(SELECT 1 FROM conversion_events e WHERE e.opportunity_id=co.id AND e.stage='CLIENT_POSITIVE_REPLY' AND e.occurred_at BETWEEN ? AND ?) success FROM client_opportunities co JOIN companies c ON c.id=co.company_id LEFT JOIN company_profiles cp ON cp.id=c.current_profile_id LEFT JOIN decision_maker_selections d ON d.company_id=c.id AND d.active=1 LEFT JOIN people p ON p.id=d.primary_person_id LEFT JOIN contacts ct ON ct.person_id=p.id LEFT JOIN service_matches sm ON sm.id=(SELECT x.id FROM service_matches x WHERE x.opportunity_id=co.id ORDER BY x.created_at DESC LIMIT 1) LEFT JOIN services sv ON sv.id=sm.primary_service_id WHERE co.discovered_at BETWEEN ? AND ?`).all(start,end,start,end)as Array<{industry:string;stage:string;role:string;contactType:string;service:string;success:number}>;return{industry:cohortAnalysis(rows,r=>r.industry,r=>Boolean(r.success)),stage:cohortAnalysis(rows,r=>r.stage,r=>Boolean(r.success)),decisionMaker:cohortAnalysis(rows,r=>r.role,r=>Boolean(r.success)),contactType:cohortAnalysis(rows,r=>r.contactType,r=>Boolean(r.success)),service:cohortAnalysis(rows,r=>r.service,r=>Boolean(r.success))};}
 insights(start:string,end:string){const cohorts=this.cohorts(start,end) as Record<string,Array<{cohort:string;sampleSize:number;successCount:number;rate:number;baselineRate:number;reliability:string}>>;return Object.entries(cohorts).flatMap(([dimension,rows])=>rows.filter((row)=>row.reliability!=='LOW'&&row.rate>row.baselineRate).slice(0,2).map((row)=>({dimension,...row,message:`${row.cohort} converts at ${(row.rate*100).toFixed(1)}% versus ${(row.baselineRate*100).toFixed(1)}% baseline (N=${row.sampleSize}).`}))) }
 dataQuality(){return this.connection.sqlite.prepare(`SELECT (SELECT COUNT(*) FROM companies WHERE COALESCE(resolved_domain,domain) IS NULL) companiesWithoutDomains,(SELECT COUNT(*) FROM company_research_runs WHERE status='FAILED') researchFailures,(SELECT COUNT(*) FROM company_profiles WHERE research_confidence<.6) lowConfidenceResearch,(SELECT COUNT(*) FROM companies c WHERE NOT EXISTS(SELECT 1 FROM decision_maker_selections d WHERE d.company_id=c.id AND d.active=1)) missingDecisionMakers,(SELECT COUNT(*) FROM decision_maker_selections d WHERE d.active=1 AND NOT EXISTS(SELECT 1 FROM contacts ct WHERE ct.person_id=d.primary_person_id)) missingContacts,(SELECT COUNT(*) FROM contacts WHERE status='PATTERN_INFERRED') inferredContacts,(SELECT COUNT(*) FROM companies WHERE next_research_after<datetime('now')) staleResearch,(SELECT COUNT(*) FROM email_send_attempts WHERE status IN('FAILED','UNKNOWN')) failedEmailSends,(SELECT COUNT(*) FROM email_messages m WHERE direction='INBOUND' AND NOT EXISTS(SELECT 1 FROM reply_classifications r WHERE r.email_message_id=m.id)) unclassifiedReplies,(SELECT COUNT(*) FROM jobs WHERE posted_at IS NULL) jobsMissingDates`).get();}
 trainingRows(funnel:'CLIENT'|'JOB',target:string){const targetStage=target;const sql=funnel==='CLIENT'?`SELECT co.current_score score,(SELECT COUNT(*) FROM signals s WHERE s.company_id=co.company_id) signalCount,COALESCE(cp.research_confidence,0) confidence,EXISTS(SELECT 1 FROM conversion_events e WHERE e.opportunity_id=co.id AND e.stage=?) label,co.discovered_at occurredAt FROM client_opportunities co LEFT JOIN companies c ON c.id=co.company_id LEFT JOIN company_profiles cp ON cp.id=c.current_profile_id`:`SELECT jo.current_score score,COALESCE(ap.match_score,0) matchScore,CASE WHEN j.posted_at IS NULL THEN 30 ELSE MIN(30,julianday(jo.discovered_at)-julianday(j.posted_at)) END age,EXISTS(SELECT 1 FROM conversion_events e WHERE e.opportunity_id=jo.id AND e.stage=?) label,jo.discovered_at occurredAt FROM job_opportunities jo JOIN jobs j ON j.id=jo.job_id LEFT JOIN application_packages ap ON ap.opportunity_id=jo.id`;const rows=this.connection.sqlite.prepare(sql).all(targetStage)as Array<Record<string,unknown>>;return rows.map(row=>({features:funnel==='CLIENT'?[Number(row.score)/100,Number(row.signalCount)/10,Number(row.confidence)]:[Number(row.score)/100,Number(row.matchScore)/100,Number(row.age)/30],label:Number(row.label)?1:0,occurredAt:String(row.occurredAt)}as TrainingRow));}
 evaluateModel(funnel:'CLIENT'|'JOB',target:string,minimumSamples=100){const rows=this.trainingRows(funnel,target),eligibility=modelEligibility(rows,minimumSamples,Math.max(10,Math.floor(minimumSamples*.1)));if(!eligibility.eligible)return{status:'INSUFFICIENT_DATA',...eligibility};const ordered=[...rows].sort((a,b)=>a.occurredAt.localeCompare(b.occurredAt)),split=Math.max(1,Math.floor(ordered.length*.8)),train=ordered.slice(0,split),test=ordered.slice(split);const model=trainLogisticRegression(train),probabilities=test.map(row=>predictProbability(model,row.features)),metrics=evaluateProbability(test.map(row=>row.label),probabilities),now=iso(),id=randomUUID(),calibration=metrics.calibrationStatus;this.db.insert(modelSnapshots).values({id,funnel,target,modelVersion:'logistic-v1',featureVersion:`${funnel.toLowerCase()}-v1`,trainingWindowStart:ordered[0]?.occurredAt,trainingWindowEnd:ordered.at(-1)!.occurredAt,sampleSize:rows.length,positiveCount:eligibility.positiveCount,featureListJson:JSON.stringify(funnel==='CLIENT'?['score','signalCount','researchConfidence']:['score','candidateMatch','jobAge']),coefficientsJson:JSON.stringify(model),metricsJson:JSON.stringify(metrics),calibrationStatus:calibration,status:calibration==='POOR'?'EVALUATED_NOT_SURFACED':'ACTIVE',createdAt:now}).run();return{status:calibration==='POOR'?'POOR_CALIBRATION':'TRAINED',snapshotId:id,...eligibility,metrics};}
 generateRecommendations(){const analytics=this.analytics(),now=iso(),created=[]as string[];for(const insight of analytics.insights){const id=randomUUID();this.db.insert(learningRecommendations).values({id,type:'WEIGHT_SUGGESTION',funnel:'CLIENT',feature:`${insight.dimension}:${insight.cohort}`,reason:insight.message,sampleSize:insight.sampleSize,successCount:insight.successCount,rate:insight.rate,baselineRate:insight.baselineRate,reliability:insight.reliability,status:'PENDING',createdAt:now,updatedAt:now}).onConflictDoNothing().run();created.push(id);}return{created:created.length};}
 decideRecommendation(id:string,status:'ACCEPTED'|'REJECTED'|'IGNORED'){this.db.update(learningRecommendations).set({status,decidedAt:iso(),updatedAt:iso()}).where(eq(learningRecommendations.id,id)).run();return this.db.select().from(learningRecommendations).where(eq(learningRecommendations.id,id)).get();}
 listRecommendations(){return this.db.select().from(learningRecommendations).orderBy(desc(learningRecommendations.createdAt)).all();}
 exportCsv(kind:string){const allowed:Record<string,string>={clients:`SELECT co.*,c.canonical_name companyName,c.domain FROM client_opportunities co JOIN companies c ON c.id=co.company_id`,jobs:`SELECT jo.*,j.title,j.location,j.posted_at FROM job_opportunities jo JOIN jobs j ON j.id=jo.job_id`,applications:`SELECT * FROM applications`,contacts:`SELECT contact_value,type,status,confidence,first_discovered_at,last_checked_at FROM contacts`,campaigns:`SELECT * FROM campaigns`,conversions:`SELECT * FROM conversion_events`};const sql=allowed[kind];if(!sql)throw new Error('Unsupported export');return toCsv(this.connection.sqlite.prepare(sql).all()as Record<string,unknown>[]);}
 async backup(directory:string){fs.mkdirSync(directory,{recursive:true});const stamp=new Date().toISOString().replace(/[:.]/g,'-'),target=path.join(directory,`gtm-${stamp}.db`),id=randomUUID(),now=iso();this.db.insert(backupHistory).values({id,path:target,status:'RUNNING',createdAt:now}).run();try{await this.connection.sqlite.backup(target);const size=fs.statSync(target).size;this.db.update(backupHistory).set({status:'COMPLETED',sizeBytes:size,completedAt:iso()}).where(eq(backupHistory.id,id)).run();return{path:target,sizeBytes:size};}catch(error){this.db.update(backupHistory).set({status:'FAILED',errorJson:JSON.stringify({message:String(error)}),completedAt:iso()}).where(eq(backupHistory.id,id)).run();throw error;}}
}
function iso(){return new Date().toISOString();}function rates(base:number,data:Record<string,unknown>){return Object.fromEntries(Object.entries(data).filter(([,v])=>typeof v==='number').map(([k,v])=>[`${k}Rate`,base?Number(v)/base:null]));}function toCsv(rows:Record<string,unknown>[]){if(!rows.length)return'';const columns=Object.keys(rows[0]!);const cell=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;return[columns.map(cell).join(','),...rows.map(row=>columns.map(key=>cell(row[key])).join(','))].join('\n');}
