import { randomUUID } from 'node:crypto';
import { and, desc, eq, lte } from 'drizzle-orm';
import { assertTransition } from '@gtm/shared';
import { SERVICE_CATALOG, assertSendAllowed, buildOutreachStrategy, followupDates, groundedApplicationFallback, groundedOutreachFallback, isHighIntent, matchCandidate, matchService, normalizeSubject, stableHash, type OutreachBundle } from '@gtm/operations';
import type { DatabaseConnection } from './client.js';
import { activities, applicationMaterialVersions, applicationPackages, applications, candidateProfiles, candidateProjects, clientOpportunities, contacts, conversionEvents, deals, emailMessages, emailSendAttempts, emailThreads, followupSequences, followupSteps, jobOpportunities, outreachMessageEvidence, outreachMessages, outreachMessageVersions, outreachStrategies, replyClassifications, serviceMatches, services, suppressionList, tasks, workerJobs } from './schema.js';

export class OperationsRepository {
  constructor(private readonly connection: DatabaseConnection) {}
  private get db() { return this.connection.db; }

  seedServices() { const now=iso(); for(const [slug,name] of SERVICE_CATALOG)this.db.insert(services).values({id:randomUUID(),slug,name,createdAt:now,updatedAt:now}).onConflictDoNothing().run(); return this.db.select().from(services).all(); }

  prepareClient(opportunityId:string, options:{force?:boolean}={}) {
    this.seedServices(); const context=this.clientContext(opportunityId); if(!context.personId) throw new Error('Select a decision maker before preparing outreach');
    const evidenceRows=this.connection.sqlite.prepare(`SELECT DISTINCT e.id,e.claim,e.confidence,s.type FROM evidence e LEFT JOIN evidence_signals es ON es.evidence_id=e.id LEFT JOIN signals s ON s.id=es.signal_id WHERE e.company_id=? ORDER BY e.confidence DESC LIMIT 20`).all(context.companyId) as Array<{id:string;claim:string;confidence:number;type:string|null}>;
    const signalRows=evidenceRows.map((row)=>({id:row.id,type:row.type??'COMPANY_EVIDENCE',claim:row.claim,confidence:row.confidence}));
    const matched=matchService(signalRows,context.jobTitle??''); const primary=this.db.select().from(services).where(eq(services.slug,matched.primarySlug)).get()!; const secondary=matched.secondarySlug?this.db.select().from(services).where(eq(services.slug,matched.secondarySlug)).get():null;
    const inputHash=stableHash({signals:signalRows,title:context.jobTitle,primary:matched.primarySlug}); let serviceMatch=this.db.select().from(serviceMatches).where(and(eq(serviceMatches.opportunityId,opportunityId),eq(serviceMatches.inputHash,inputHash))).get(); const now=iso();
    if(!serviceMatch){const id=randomUUID();this.db.insert(serviceMatches).values({id,opportunityId,companyId:context.companyId,primaryServiceId:primary.id,secondaryServiceId:secondary?.id,confidence:matched.confidence,reason:matched.reason,evidenceIdsJson:JSON.stringify(matched.evidenceIds),inputHash,createdAt:now}).run();serviceMatch=this.db.select().from(serviceMatches).where(eq(serviceMatches.id,id)).get()!;this.activity('CLIENT_OPPORTUNITY',opportunityId,'SERVICE_MATCHED',{primaryService:primary.name,serviceMatchId:id});}
    const evidenceHash=stableHash(evidenceRows.map(({id,claim})=>({id,claim}))); const strategyDraft=buildOutreachStrategy({opportunityId,companyId:context.companyId,personId:context.personId,...(context.contactId?{contactId:context.contactId}:{}),serviceName:primary.name,serviceMatchId:serviceMatch.id,signals:signalRows,evidenceHash});
    let strategy=this.db.select().from(outreachStrategies).where(and(eq(outreachStrategies.opportunityId,opportunityId),eq(outreachStrategies.personId,context.personId),eq(outreachStrategies.serviceMatchId,serviceMatch.id),eq(outreachStrategies.evidenceHash,evidenceHash),eq(outreachStrategies.promptVersion,strategyDraft.promptVersion))).get();
    if(!strategy){const id=randomUUID();this.db.insert(outreachStrategies).values({id,opportunityId,companyId:context.companyId,personId:context.personId,contactId:context.contactId,serviceMatchId:serviceMatch.id,primarySignal:strategyDraft.primarySignal,angle:strategyDraft.angle,cta:strategyDraft.cta,confidence:strategyDraft.confidence,evidenceHash,promptVersion:strategyDraft.promptVersion,createdAt:now}).run();strategy=this.db.select().from(outreachStrategies).where(eq(outreachStrategies.id,id)).get()!;}
    const existing=this.db.select().from(outreachMessages).where(eq(outreachMessages.strategyId,strategy.id)).all();
    if(existing.length&&!options.force)return {cached:true,serviceMatch,strategy,messages:existing};
    if(existing.length&&options.force){for(const message of existing)this.db.update(outreachMessages).set({status:'DRAFT',staleReason:'Explicit regeneration requested',updatedAt:now}).where(eq(outreachMessages.id,message.id)).run();return {cached:false,serviceMatch,strategy,messages:existing};}
    const bestEvidence=evidenceRows[0]; if(!bestEvidence)throw new Error('Evidence is required before outreach generation');
    const bundle=groundedOutreachFallback({firstName:context.firstName!,companyName:context.companyName,evidenceClaim:bestEvidence.claim,serviceName:primary.name,angle:strategy.angle,cta:strategy.cta});
    const created=this.saveOutreachBundle(strategy.id,bundle,evidenceRows.map((row)=>row.id),{primaryService:primary.name,primarySignal:strategy.primarySignal,ctaType:'SEND_EXAMPLES'});
    this.setClientStatus(opportunityId,'DRAFT_READY','SYSTEM',{strategyId:strategy.id}); this.setClientStatus(opportunityId,'AWAITING_APPROVAL','SYSTEM',{strategyId:strategy.id});
    this.createTask('APPROVE_EMAIL','CLIENT_OPPORTUNITY',opportunityId,context.score,null,{messageId:created[0]?.id});
    return {cached:false,serviceMatch,strategy,messages:created};
  }

  private saveOutreachBundle(strategyId:string,bundle:OutreachBundle,evidenceIds:string[],metadata:Record<string,unknown>) {
    const strategy=this.db.select().from(outreachStrategies).where(eq(outreachStrategies.id,strategyId)).get()!;
    const now=iso();
    const specs=[{channel:'EMAIL',n:0,body:bundle.coldEmail,subjects:bundle.subjects},{channel:'LINKEDIN',n:0,body:bundle.linkedIn,subjects:[]},...bundle.followups.map((body,index)=>({channel:'EMAIL',n:index+1,body,subjects:bundle.subjects.slice(0,1)}))];
    return this.db.transaction((tx)=>specs.map((spec)=>{
      const id=randomUUID(),versionId=randomUUID();
      tx.insert(outreachMessages).values({id,opportunityId:strategy.opportunityId,strategyId,campaignId:null,channel:spec.channel,followupNumber:spec.n,status:'DRAFT',currentVersionId:versionId,createdAt:now,updatedAt:now}).run();
      tx.insert(outreachMessageVersions).values({id:versionId,messageId:id,version:1,subjectsJson:JSON.stringify(spec.subjects),textBody:spec.body,createdBy:'AI_FALLBACK',status:'GENERATED',promptVersion:strategy.promptVersion,evidenceHash:strategy.evidenceHash,metadataJson:JSON.stringify({...metadata,followUpNumber:spec.n,channel:spec.channel}),createdAt:now}).run();
      for(const evidenceId of evidenceIds)tx.insert(outreachMessageEvidence).values({id:randomUUID(),messageVersionId:versionId,evidenceId,createdAt:now}).run();
      tx.insert(activities).values({id:randomUUID(),entityType:'OUTREACH_MESSAGE',entityId:id,type:'OUTREACH_GENERATED',actor:'SYSTEM',metadataJson:JSON.stringify({versionId}),occurredAt:now,createdAt:now}).run();
      return tx.select().from(outreachMessages).where(eq(outreachMessages.id,id)).get()!;
    }));
  }

  editMessage(messageId:string,input:{textBody:string;subjects?:string[]}) {const message=this.requireMessage(messageId),parent=this.currentVersion(message),now=iso();const count=this.db.select().from(outreachMessageVersions).where(eq(outreachMessageVersions.messageId,messageId)).all().length;const id=randomUUID();this.db.transaction((tx)=>{tx.insert(outreachMessageVersions).values({id,messageId,version:count+1,parentVersionId:parent.id,subjectsJson:JSON.stringify(input.subjects??parseArray(parent.subjectsJson)),textBody:input.textBody,htmlBody:parent.htmlBody,createdBy:'USER',status:'EDITED',promptVersion:parent.promptVersion,evidenceHash:parent.evidenceHash,metadataJson:parent.metadataJson,createdAt:now}).run();tx.update(outreachMessages).set({currentVersionId:id,status:'DRAFT',updatedAt:now}).where(eq(outreachMessages.id,messageId)).run();});this.activity('OUTREACH_MESSAGE',messageId,'MESSAGE_EDITED',{versionId:id});return {id,version:count+1};}
  approveMessage(messageId:string,confirmedInferred=false) {const message=this.requireMessage(messageId),version=this.currentVersion(message),now=iso();const strategy=this.db.select().from(outreachStrategies).where(eq(outreachStrategies.id,message.strategyId)).get()!;const contact=strategy.contactId?this.db.select().from(contacts).where(eq(contacts.id,strategy.contactId)).get():null;if(message.channel==='EMAIL'&&!contact)throw new Error('An email contact is required');if(contact?.status==='PATTERN_INFERRED'&&!confirmedInferred)throw new Error('Pattern-inferred contact requires explicit confirmation');this.db.transaction((tx)=>{tx.update(outreachMessageVersions).set({status:'APPROVED',metadataJson:JSON.stringify({...parseObject(version.metadataJson),confirmedInferred})}).where(eq(outreachMessageVersions.id,version.id)).run();tx.update(outreachMessages).set({status:'APPROVED',approvedAt:now,updatedAt:now}).where(eq(outreachMessages.id,messageId)).run();tx.update(tasks).set({status:'COMPLETED',completedAt:now,updatedAt:now}).where(and(eq(tasks.entityType,'CLIENT_OPPORTUNITY'),eq(tasks.entityId,message.opportunityId),eq(tasks.type,'APPROVE_EMAIL'),eq(tasks.status,'OPEN'))).run();});this.setClientStatus(message.opportunityId,'APPROVED','USER',{messageId,versionId:version.id});this.activity('OUTREACH_MESSAGE',messageId,'MESSAGE_APPROVED',{versionId:version.id});return {messageId,versionId:version.id};}
  queueSend(messageId:string){const message=this.requireMessage(messageId);if(message.status!=='APPROVED')throw new Error('Message must be approved');return this.enqueue('SEND_EMAIL',{messageId},`send:${messageId}:${message.currentVersionId}`,100);}

  beginSend(messageId:string,limits:{minimumConfidence:number;hourlyLimit:number;dailyLimit:number}) {const message=this.requireMessage(messageId),version=this.currentVersion(message),strategy=this.db.select().from(outreachStrategies).where(eq(outreachStrategies.id,message.strategyId)).get()!,contact=strategy.contactId?this.db.select().from(contacts).where(eq(contacts.id,strategy.contactId)).get():null;if(!contact)throw new Error('Contact not found');const suppressed=this.connection.sqlite.prepare(`SELECT 1 FROM suppression_list WHERE normalized_value=? AND active=1 LIMIT 1`).get(contact.normalizedValue);const hour=new Date(Date.now()-3_600_000).toISOString(),day=new Date(Date.now()-86_400_000).toISOString();const sentHour=(this.connection.sqlite.prepare(`SELECT COUNT(*) count FROM email_send_attempts WHERE status='SENT' AND completed_at>=?`).get(hour) as {count:number}).count;const sentDay=(this.connection.sqlite.prepare(`SELECT COUNT(*) count FROM email_send_attempts WHERE status='SENT' AND completed_at>=?`).get(day) as {count:number}).count;const idempotencyKey=stableHash({messageId,recipient:contact.normalizedValue,versionId:version.id});const existing=this.db.select().from(emailSendAttempts).where(eq(emailSendAttempts.idempotencyKey,idempotencyKey)).get();assertSendAllowed({status:message.status,suppressed:Boolean(suppressed),unsubscribed:false,permanentlyBounced:false,contactConfidence:contact.confidence,minimumConfidence:limits.minimumConfidence,inferred:contact.status==='PATTERN_INFERRED',inferredConfirmed:Boolean(parseObject(version.metadataJson).confirmedInferred),sentCountHour:sentHour,sentCountDay:sentDay,hourlyLimit:limits.hourlyLimit,dailyLimit:limits.dailyLimit,alreadySent:existing?.status==='SENT'||existing?.status==='SENDING'||existing?.status==='UNKNOWN'});const now=iso(),attemptId=existing?.id??randomUUID();if(existing)this.db.update(emailSendAttempts).set({status:'SENDING',attempts:existing.attempts+1,startedAt:now,updatedAt:now,errorJson:null}).where(eq(emailSendAttempts.id,attemptId)).run();else this.db.insert(emailSendAttempts).values({id:attemptId,outreachMessageId:messageId,messageVersionId:version.id,recipient:contact.normalizedValue,idempotencyKey,status:'SENDING',attempts:1,startedAt:now,createdAt:now,updatedAt:now}).run();return {attemptId,message,version,contact,strategy,subject:parseArray(version.subjectsJson)[0]??'Quick note'};}

  finishSend(attemptId:string,result:{messageId:string;response?:unknown}) {const attempt=this.db.select().from(emailSendAttempts).where(eq(emailSendAttempts.id,attemptId)).get();if(!attempt)throw new Error('Send attempt not found');const message=this.requireMessage(attempt.outreachMessageId),strategy=this.db.select().from(outreachStrategies).where(eq(outreachStrategies.id,message.strategyId)).get()!,version=this.currentVersion(message),now=iso();let thread=this.db.select().from(emailThreads).where(eq(emailThreads.opportunityId,message.opportunityId)).orderBy(desc(emailThreads.lastMessageAt)).get();const subject=String(parseArray(version.subjectsJson)[0]??'Quick note');this.db.transaction((tx)=>{if(!thread){const id=randomUUID();tx.insert(emailThreads).values({id,opportunityId:message.opportunityId,personId:strategy.personId,contactId:strategy.contactId,subject,normalizedSubject:normalizeSubject(subject),lastMessageAt:now,createdAt:now,updatedAt:now}).run();thread=tx.select().from(emailThreads).where(eq(emailThreads.id,id)).get()!;}tx.insert(emailMessages).values({id:randomUUID(),threadId:thread!.id,outreachMessageId:message.id,direction:'OUTBOUND',messageId:result.messageId,sender:'configured-sender',recipientsJson:JSON.stringify([attempt.recipient]),subject,textBody:version.textBody,htmlBody:version.htmlBody,rawMetadataJson:JSON.stringify(result.response??{}),occurredAt:now,createdAt:now}).run();tx.update(emailSendAttempts).set({status:'SENT',providerMessageId:result.messageId,providerResponseJson:JSON.stringify(result.response??{}),completedAt:now,updatedAt:now}).where(eq(emailSendAttempts.id,attemptId)).run();tx.update(outreachMessages).set({status:'SENT',sentAt:now,updatedAt:now}).where(eq(outreachMessages.id,message.id)).run();});if(message.followupNumber===0&&message.channel==='EMAIL')this.startFollowups(message.opportunityId,thread!.id,now);this.setClientStatus(message.opportunityId,message.followupNumber?'FOLLOW_UP':'CONTACTED','SYSTEM',{messageId:message.id});this.conversion('CLIENT',message.opportunityId,'CLIENT_CONTACTED',{channel:'EMAIL',messageVersionId:version.id});return {threadId:thread!.id};}
  failSend(attemptId:string,error:unknown,uncertain=false){this.db.update(emailSendAttempts).set({status:uncertain?'UNKNOWN':'FAILED',errorJson:JSON.stringify({message:error instanceof Error?error.message:String(error)}),completedAt:iso(),updatedAt:iso()}).where(eq(emailSendAttempts.id,attemptId)).run();}

  private startFollowups(opportunityId:string,threadId:string,sentAt:string){const current=this.db.select().from(followupSequences).where(and(eq(followupSequences.opportunityId,opportunityId),eq(followupSequences.status,'ACTIVE'))).get();if(current)return current;const now=iso(),id=randomUUID(),dates=followupDates(new Date(sentAt));const msgs=this.connection.sqlite.prepare(`SELECT id,followup_number FROM outreach_messages WHERE opportunity_id=? AND followup_number>0 ORDER BY followup_number`).all(opportunityId) as Array<{id:string;followup_number:number}>;this.db.transaction((tx)=>{tx.insert(followupSequences).values({id,opportunityId,threadId,status:'ACTIVE',approvalMode:'MANUAL_APPROVAL',nextDueAt:dates[0],createdAt:now,updatedAt:now}).run();for(const message of msgs){const dueAt=dates[message.followup_number-1];if(dueAt)tx.insert(followupSteps).values({id:randomUUID(),sequenceId:id,outreachMessageId:message.id,stepNumber:message.followup_number,dueAt,status:'SCHEDULED',createdAt:now,updatedAt:now}).run();}});return {id};}
  processDueFollowups(){const now=iso();const due=this.db.select().from(followupSteps).where(and(eq(followupSteps.status,'SCHEDULED'),lte(followupSteps.dueAt,now))).all();for(const step of due){this.db.update(followupSteps).set({status:'AWAITING_APPROVAL',updatedAt:now}).where(eq(followupSteps.id,step.id)).run();this.db.update(outreachMessages).set({status:'AWAITING_APPROVAL',updatedAt:now}).where(eq(outreachMessages.id,step.outreachMessageId)).run();this.createTask('SEND_FOLLOWUP','OUTREACH_MESSAGE',step.outreachMessageId,80,step.dueAt,{stepNumber:step.stepNumber});}return {due:due.length};}
  stopFollowups(opportunityId:string,reason:string){const now=iso();this.db.update(followupSequences).set({status:'STOPPED',stopReason:reason,nextDueAt:null,updatedAt:now}).where(and(eq(followupSequences.opportunityId,opportunityId),eq(followupSequences.status,'ACTIVE'))).run();this.connection.sqlite.prepare(`UPDATE followup_steps SET status='CANCELLED',updated_at=? WHERE sequence_id IN (SELECT id FROM followup_sequences WHERE opportunity_id=?) AND status IN ('SCHEDULED','AWAITING_APPROVAL')`).run(now,opportunityId);}

  ingestReply(input:{threadId:string;messageId:string;inReplyTo?:string;references?:string[];sender:string;recipients:string[];subject:string;textBody:string;occurredAt?:string}){const exists=this.db.select().from(emailMessages).where(eq(emailMessages.messageId,input.messageId)).get();if(exists)return {cached:true,emailMessageId:exists.id};const thread=this.db.select().from(emailThreads).where(eq(emailThreads.id,input.threadId)).get();if(!thread)throw new Error('Email thread not found');const now=input.occurredAt??iso(),id=randomUUID();this.db.insert(emailMessages).values({id,threadId:thread.id,direction:'INBOUND',messageId:input.messageId,inReplyTo:input.inReplyTo,referencesJson:JSON.stringify(input.references??[]),sender:input.sender,recipientsJson:JSON.stringify(input.recipients),subject:input.subject,textBody:input.textBody,rawMetadataJson:'{}',occurredAt:now,createdAt:iso()}).run();this.db.update(emailThreads).set({lastMessageAt:now,updatedAt:iso()}).where(eq(emailThreads.id,thread.id)).run();this.stopFollowups(thread.opportunityId!,'REPLY_RECEIVED');return {cached:false,emailMessageId:id,opportunityId:thread.opportunityId};}
  saveReplyClassification(emailMessageId:string,result:{classification:string;confidence:number;reason:string;classifier:string;model?:string;promptVersion?:string}){const email=this.db.select().from(emailMessages).where(eq(emailMessages.id,emailMessageId)).get();if(!email)throw new Error('Email not found');const thread=this.db.select().from(emailThreads).where(eq(emailThreads.id,email.threadId)).get()!,now=iso();this.db.insert(replyClassifications).values({id:randomUUID(),emailMessageId,...result,createdAt:now}).run();if(thread.opportunityId){const positive=isHighIntent(result.classification);this.setClientStatus(thread.opportunityId,positive?'POSITIVE_REPLY':'REPLIED','SYSTEM',{classification:result.classification,emailMessageId});this.conversion('CLIENT',thread.opportunityId,positive?'CLIENT_POSITIVE_REPLY':'CLIENT_REPLIED',{classification:result.classification});if(positive)this.createTask('REPLY_TO_LEAD','CLIENT_OPPORTUNITY',thread.opportunityId,100,now,{emailMessageId,classification:result.classification});if(['UNSUBSCRIBE','BOUNCE','NOT_INTERESTED'].includes(result.classification)){const contact=thread.contactId?this.db.select().from(contacts).where(eq(contacts.id,thread.contactId)).get():null;if(contact)this.suppress(contact.contactValue,result.classification==='BOUNCE'?'BOUNCED':result.classification==='UNSUBSCRIBE'?'UNSUBSCRIBED':'NOT_INTERESTED',emailMessageId);}}
    return result;}
  suppress(value:string,reason:string,sourceEntityId?:string){this.db.insert(suppressionList).values({id:randomUUID(),contactValue:value,normalizedValue:value.trim().toLowerCase(),reason,sourceEntityId,createdAt:iso()}).run();}

  saveCandidateProfile(input:{name:string;professionalTitle:string;summary:string;skills:string[];technologies:string[];experience:unknown[];portfolioUrl?:string;githubUrl?:string;linkedinUrl?:string;preferences?:Record<string,unknown>;projects?:Array<{name:string;description:string;problem?:string;solution?:string;technologies:string[];aiCapabilities?:string[];industry?:string;url?:string;repositoryUrl?:string;results?:string}>}){const hash=stableHash(input),existing=this.db.select().from(candidateProfiles).where(eq(candidateProfiles.inputHash,hash)).get();if(existing)return existing;const now=iso(),version=this.db.select().from(candidateProfiles).all().length+1,id=randomUUID();this.db.transaction((tx)=>{tx.update(candidateProfiles).set({active:false,updatedAt:now}).where(eq(candidateProfiles.active,true)).run();tx.insert(candidateProfiles).values({id,version,name:input.name,professionalTitle:input.professionalTitle,summary:input.summary,skillsJson:JSON.stringify(input.skills),technologiesJson:JSON.stringify(input.technologies),experienceJson:JSON.stringify(input.experience),portfolioUrl:input.portfolioUrl,githubUrl:input.githubUrl,linkedinUrl:input.linkedinUrl,preferencesJson:JSON.stringify(input.preferences??{}),inputHash:hash,active:true,createdAt:now,updatedAt:now}).run();for(const project of input.projects??[])tx.insert(candidateProjects).values({id:randomUUID(),candidateProfileId:id,name:project.name,description:project.description,problem:project.problem,solution:project.solution,technologiesJson:JSON.stringify(project.technologies),aiCapabilitiesJson:JSON.stringify(project.aiCapabilities??[]),industry:project.industry,url:project.url,repositoryUrl:project.repositoryUrl,results:project.results,createdAt:now,updatedAt:now}).run();});return this.db.select().from(candidateProfiles).where(eq(candidateProfiles.id,id)).get()!;}
  prepareApplication(opportunityId:string,force=false){const profile=this.db.select().from(candidateProfiles).where(eq(candidateProfiles.active,true)).orderBy(desc(candidateProfiles.version)).get();if(!profile)throw new Error('Create a candidate profile first');const row=this.connection.sqlite.prepare(`SELECT jo.id,j.title,j.description,j.location,j.fingerprint,c.canonical_name companyName,js.source_url applicationUrl FROM job_opportunities jo JOIN jobs j ON j.id=jo.job_id JOIN companies c ON c.id=j.company_id LEFT JOIN job_sources js ON js.job_id=j.id WHERE jo.id=? LIMIT 1`).get(opportunityId) as Record<string,unknown>|undefined;if(!row)throw new Error('Job opportunity not found');const projects=this.db.select().from(candidateProjects).where(eq(candidateProjects.candidateProfileId,profile.id)).all();const candidate={summary:profile.summary,skills:parseArray(profile.skillsJson),technologies:parseArray(profile.technologiesJson),experience:parseUnknownArray(profile.experienceJson),projects:projects.map((p)=>({id:p.id,name:p.name,description:p.description,technologies:parseArray(p.technologiesJson),results:p.results}))};const job={title:String(row.title),description:String(row.description),location:String(row.location)};const match=matchCandidate(candidate,job),jobHash=stableHash({fingerprint:row.fingerprint,description:row.description}),existing=this.db.select().from(applicationPackages).where(and(eq(applicationPackages.opportunityId,opportunityId),eq(applicationPackages.candidateProfileHash,profile.inputHash),eq(applicationPackages.jobHash,jobHash),eq(applicationPackages.promptVersion,'application-v1'))).get();if(existing&&!force)return {cached:true,package:existing};const materials=groundedApplicationFallback(candidate,{title:job.title,companyName:String(row.companyName)},match),now=iso(),id=randomUUID(),versionId=randomUUID();this.db.transaction((tx)=>{tx.insert(applicationPackages).values({id,opportunityId,candidateProfileId:profile.id,candidateProfileHash:profile.inputHash,jobHash,status:'READY',matchScore:match.matchScore,matchJson:JSON.stringify(match),currentVersionId:versionId,promptVersion:'application-v1',createdAt:now,updatedAt:now}).run();tx.insert(applicationMaterialVersions).values({id:versionId,packageId:id,version:1,materialsJson:JSON.stringify(materials),createdBy:'DETERMINISTIC',status:'GENERATED',createdAt:now}).run();});this.activity('JOB_OPPORTUNITY',opportunityId,'APPLICATION_PACKAGE_GENERATED',{packageId:id,matchScore:match.matchScore});this.createTask('APPLY_TO_JOB','JOB_OPPORTUNITY',opportunityId,match.matchScore,null,{packageId:id});return {cached:false,package:this.db.select().from(applicationPackages).where(eq(applicationPackages.id,id)).get(),match,materials};}
  markApplied(opportunityId:string,input:{packageId?:string;applicationUrl:string;source:string;resumeVersionId?:string;notes?:string}){const now=iso(),id=randomUUID();let current=this.db.select().from(jobOpportunities).where(eq(jobOpportunities.id,opportunityId)).get();if(!current)throw new Error('Job opportunity not found');if(current.status==='DISCOVERED'){this.setJobStatus(opportunityId,'QUALIFIED','USER');current=this.db.select().from(jobOpportunities).where(eq(jobOpportunities.id,opportunityId)).get()!;}if(current.status==='QUALIFIED')this.setJobStatus(opportunityId,'READY_TO_APPLY','USER');this.db.insert(applications).values({id,opportunityId,packageId:input.packageId,applicationUrl:input.applicationUrl,source:input.source,resumeVersionId:input.resumeVersionId,status:'APPLIED',appliedAt:now,notes:input.notes,createdAt:now,updatedAt:now}).run();this.setJobStatus(opportunityId,'APPLIED','USER',{applicationId:id});this.conversion('JOB',opportunityId,'JOB_APPLIED',{applicationId:id});this.createTask('FOLLOW_UP_JOB','JOB_OPPORTUNITY',opportunityId,60,new Date(Date.now()+5*86_400_000).toISOString(),{applicationId:id});return {id};}

  setClientStatus(opportunityId:string,toStatus:string,actor='USER',metadata:Record<string,unknown>={}){const opportunity=this.db.select().from(clientOpportunities).where(eq(clientOpportunities.id,opportunityId)).get();if(!opportunity)throw new Error('Client opportunity not found');if(opportunity.status===toStatus)return opportunity;const forward=['DISCOVERED','RESEARCHING','QUALIFIED','CONTACT_FOUND','READY_TO_CONTACT','DRAFT_READY','AWAITING_APPROVAL','APPROVED','CONTACTED','FOLLOW_UP','REPLIED','POSITIVE_REPLY','MEETING','PROPOSAL','WON','LOST'];if(!assertable('CLIENT',opportunity.status,toStatus)&&forward.indexOf(toStatus)<forward.indexOf(opportunity.status)&&!['LOST','WON'].includes(toStatus))throw new Error(`Invalid CLIENT transition: ${opportunity.status} -> ${toStatus}`);const now=iso();this.db.update(clientOpportunities).set({status:toStatus,lastActivityAt:now,updatedAt:now}).where(eq(clientOpportunities.id,opportunityId)).run();this.activity('CLIENT_OPPORTUNITY',opportunityId,'STATUS_CHANGED',{...metadata,fromStatus:opportunity.status,toStatus},actor,opportunity.status,toStatus);return this.db.select().from(clientOpportunities).where(eq(clientOpportunities.id,opportunityId)).get()!;}
  setJobStatus(opportunityId:string,toStatus:string,actor='USER',metadata:Record<string,unknown>={}){const opportunity=this.db.select().from(jobOpportunities).where(eq(jobOpportunities.id,opportunityId)).get();if(!opportunity)throw new Error('Job opportunity not found');if(opportunity.status===toStatus)return opportunity;assertTransition('JOB',opportunity.status,toStatus);const now=iso();this.db.update(jobOpportunities).set({status:toStatus,lastActivityAt:now,updatedAt:now}).where(eq(jobOpportunities.id,opportunityId)).run();this.activity('JOB_OPPORTUNITY',opportunityId,'STATUS_CHANGED',{...metadata,fromStatus:opportunity.status,toStatus},actor,opportunity.status,toStatus);const event:Record<string,string>={RECRUITER_REPLY:'JOB_REPLY',SCREENING:'JOB_SCREENING',INTERVIEW:'JOB_INTERVIEW',TECHNICAL_INTERVIEW:'JOB_TECHNICAL_INTERVIEW',OFFER:'JOB_OFFER',ACCEPTED:'JOB_ACCEPTED'};if(event[toStatus])this.conversion('JOB',opportunityId,event[toStatus],metadata);return opportunity;}
  recordClientOutcome(opportunityId:string,input:{status:'MEETING'|'PROPOSAL'|'WON'|'LOST';valueCents?:number;currency?:string;notes?:string;serviceId?:string;campaignId?:string;personId?:string}){this.setClientStatus(opportunityId,input.status,'USER',input);const event={MEETING:'CLIENT_MEETING',PROPOSAL:'CLIENT_PROPOSAL',WON:'CLIENT_WON',LOST:'CLIENT_LOST'}[input.status];this.conversion('CLIENT',opportunityId,event,{notes:input.notes},input.valueCents,input.currency);if(input.status==='WON'){const now=iso();this.db.insert(deals).values({id:randomUUID(),opportunityId,serviceId:input.serviceId,campaignId:input.campaignId,personId:input.personId,valueCents:input.valueCents,currency:input.currency??'USD',status:'WON',wonAt:now,notes:input.notes,createdAt:now,updatedAt:now}).run();}if(['MEETING','WON','LOST'].includes(input.status))this.stopFollowups(opportunityId,input.status);}
  createTask(type:string,entityType:string,entityId:string,priority:number,dueAt:string|null,metadata:Record<string,unknown>={}){const existing=this.connection.sqlite.prepare(`SELECT id FROM tasks WHERE type=? AND entity_type=? AND entity_id=? AND status='OPEN' LIMIT 1`).get(type,entityType,entityId) as {id:string}|undefined;if(existing)return existing;const now=iso(),id=randomUUID();this.db.insert(tasks).values({id,type,entityType,entityId,priority,dueAt,status:'OPEN',metadataJson:JSON.stringify(metadata),createdAt:now,updatedAt:now}).run();return {id};}
  actionCenter(){const counts=this.connection.sqlite.prepare(`SELECT (SELECT COUNT(*) FROM client_opportunities WHERE current_score>=90 AND status NOT IN ('WON','LOST')) exceptionalClientLeads,(SELECT COUNT(*) FROM tasks WHERE status='OPEN' AND type='APPROVE_EMAIL') messagesAwaitingApproval,(SELECT COUNT(*) FROM outreach_messages WHERE status='APPROVED' AND channel='EMAIL') approvedEmailsReady,(SELECT COUNT(*) FROM tasks WHERE status='OPEN' AND type='SEND_FOLLOWUP' AND (due_at IS NULL OR due_at<=datetime('now'))) followupsDue,(SELECT COUNT(*) FROM tasks WHERE status='OPEN' AND type='REPLY_TO_LEAD') positiveReplies,(SELECT COUNT(*) FROM client_opportunities WHERE status='MEETING') meetings,(SELECT COUNT(*) FROM job_opportunities WHERE current_score>=80 AND status NOT IN ('ACCEPTED','REJECTED','WITHDRAWN','EXPIRED')) highPriorityJobs,(SELECT COUNT(*) FROM application_packages WHERE status='READY') applicationsReady,(SELECT COUNT(*) FROM tasks WHERE status='OPEN' AND type='FOLLOW_UP_JOB' AND due_at<=datetime('now')) applicationsFollowup,(SELECT COUNT(*) FROM job_opportunities WHERE status='RECRUITER_REPLY') recruiterReplies,(SELECT COUNT(*) FROM job_opportunities WHERE status IN ('INTERVIEW','TECHNICAL_INTERVIEW','FINAL_INTERVIEW')) interviews`).get();const items=this.connection.sqlite.prepare(`SELECT * FROM tasks WHERE status='OPEN' ORDER BY priority DESC,COALESCE(due_at,'9999') LIMIT 50`).all();return {counts,items};}
  analytics(){const client=this.connection.sqlite.prepare(`SELECT COUNT(DISTINCT opportunity_id) discovered,COUNT(DISTINCT CASE WHEN stage='CLIENT_CONTACTED' THEN opportunity_id END) contacted,COUNT(DISTINCT CASE WHEN stage IN ('CLIENT_REPLIED','CLIENT_POSITIVE_REPLY') THEN opportunity_id END) replies,COUNT(DISTINCT CASE WHEN stage='CLIENT_POSITIVE_REPLY' THEN opportunity_id END) positiveReplies,COUNT(DISTINCT CASE WHEN stage='CLIENT_MEETING' THEN opportunity_id END) meetings,COUNT(DISTINCT CASE WHEN stage='CLIENT_PROPOSAL' THEN opportunity_id END) proposals,COUNT(DISTINCT CASE WHEN stage='CLIENT_WON' THEN opportunity_id END) won,COALESCE(SUM(CASE WHEN stage='CLIENT_WON' THEN revenue_cents END),0) revenueCents FROM conversion_events WHERE funnel='CLIENT'`).get() as Record<string,number>;const job=this.connection.sqlite.prepare(`SELECT COUNT(DISTINCT opportunity_id) discovered,COUNT(DISTINCT CASE WHEN stage='JOB_APPLIED' THEN opportunity_id END) applications,COUNT(DISTINCT CASE WHEN stage='JOB_REPLY' THEN opportunity_id END) recruiterReplies,COUNT(DISTINCT CASE WHEN stage='JOB_SCREENING' THEN opportunity_id END) screenings,COUNT(DISTINCT CASE WHEN stage IN ('JOB_INTERVIEW','JOB_TECHNICAL_INTERVIEW') THEN opportunity_id END) interviews,COUNT(DISTINCT CASE WHEN stage='JOB_OFFER' THEN opportunity_id END) offers,COUNT(DISTINCT CASE WHEN stage='JOB_ACCEPTED' THEN opportunity_id END) accepted FROM conversion_events WHERE funnel='JOB'`).get() as Record<string,number>;return {client:withRates(client,['contacted','replies','positiveReplies','meetings','proposals','won']),job:withRates(job,['applications','recruiterReplies','interviews','offers','accepted']),breakdowns:this.connection.sqlite.prepare(`SELECT funnel,stage,source_id sourceId,campaign_id campaignId,COUNT(DISTINCT opportunity_id) opportunities,SUM(COALESCE(revenue_cents,0)) revenueCents FROM conversion_events GROUP BY funnel,stage,source_id,campaign_id ORDER BY opportunities DESC`).all()};}
  getClientOperations(opportunityId:string){const serviceMatch=this.connection.sqlite.prepare(`SELECT sm.*,s.name primaryService,ss.name secondaryService FROM service_matches sm JOIN services s ON s.id=sm.primary_service_id LEFT JOIN services ss ON ss.id=sm.secondary_service_id WHERE sm.opportunity_id=? ORDER BY sm.created_at DESC LIMIT 1`).get(opportunityId);const strategy=this.connection.sqlite.prepare(`SELECT * FROM outreach_strategies WHERE opportunity_id=? ORDER BY created_at DESC LIMIT 1`).get(opportunityId) as {id?:string}|undefined;const messages=strategy?.id?this.connection.sqlite.prepare(`SELECT m.*,v.version,v.subjects_json subjectsJson,v.text_body textBody,v.created_by createdBy,v.metadata_json metadataJson FROM outreach_messages m JOIN outreach_message_versions v ON v.id=m.current_version_id WHERE m.strategy_id=? ORDER BY m.channel,m.followup_number`).all(strategy.id):[];const threads=this.connection.sqlite.prepare(`SELECT * FROM email_threads WHERE opportunity_id=? ORDER BY last_message_at DESC`).all(opportunityId);return {serviceMatch,strategy,messages,threads};}
  getJobOperations(opportunityId:string){const packages=this.connection.sqlite.prepare(`SELECT p.*,v.materials_json materialsJson FROM application_packages p LEFT JOIN application_material_versions v ON v.id=p.current_version_id WHERE p.opportunity_id=? ORDER BY p.created_at DESC`).all(opportunityId);const applicationRows=this.db.select().from(applications).where(eq(applications.opportunityId,opportunityId)).orderBy(desc(applications.createdAt)).all();return {packages,applications:applicationRows};}

  private clientContext(opportunityId:string){const row=this.connection.sqlite.prepare(`SELECT co.id,co.company_id companyId,co.current_score score,c.canonical_name companyName,j.title jobTitle,d.primary_person_id personId,p.first_name firstName,ct.id contactId FROM client_opportunities co JOIN companies c ON c.id=co.company_id LEFT JOIN jobs j ON j.id=co.trigger_job_id LEFT JOIN decision_maker_selections d ON d.company_id=c.id AND d.active=1 LEFT JOIN people p ON p.id=d.primary_person_id LEFT JOIN contacts ct ON ct.id=(SELECT x.id FROM contacts x WHERE x.person_id=p.id ORDER BY x.confidence DESC LIMIT 1) WHERE co.id=?`).get(opportunityId) as {id:string;companyId:string;score:number;companyName:string;jobTitle:string|null;personId:string|null;firstName:string|null;contactId:string|null}|undefined;if(!row)throw new Error('Client opportunity not found');return row;}
  private requireMessage(id:string){const row=this.db.select().from(outreachMessages).where(eq(outreachMessages.id,id)).get();if(!row)throw new Error('Outreach message not found');return row;}
  private currentVersion(message:typeof outreachMessages.$inferSelect){if(!message.currentVersionId)throw new Error('Message has no current version');const row=this.db.select().from(outreachMessageVersions).where(eq(outreachMessageVersions.id,message.currentVersionId)).get();if(!row)throw new Error('Message version not found');return row;}
  private enqueue(type:string,payload:Record<string,unknown>,key:string,priority:number){const now=iso(),id=randomUUID();try{this.db.insert(workerJobs).values({id,type,payloadJson:JSON.stringify(payload),status:'PENDING',priority,attempts:0,maxAttempts:3,runAfter:now,idempotencyKey:key,createdAt:now}).run();return {id};}catch{return this.db.select().from(workerJobs).where(eq(workerJobs.idempotencyKey,key)).get();}}
  private activity(entityType:string,entityId:string,type:string,metadata:Record<string,unknown>,actor='SYSTEM',fromStatus?:string,toStatus?:string){const now=iso();this.db.insert(activities).values({id:randomUUID(),entityType,entityId,type,actor,fromStatus,toStatus,metadataJson:JSON.stringify(metadata),occurredAt:now,createdAt:now}).run();}
  private conversion(funnel:string,opportunityId:string,stage:string,metadata:Record<string,unknown>,revenueCents?:number,currency?:string){const now=iso();this.db.insert(conversionEvents).values({id:randomUUID(),funnel,opportunityId,stage,revenueCents,currency:currency??'USD',metadataJson:JSON.stringify(metadata),occurredAt:now,createdAt:now}).run();}
}
function iso(){return new Date().toISOString();}
function parseArray(value:string):string[]{try{const parsed=JSON.parse(value) as unknown;return Array.isArray(parsed)?parsed.filter((x):x is string=>typeof x==='string'):[];}catch{return[];}}
function parseUnknownArray(value:string):unknown[]{try{const parsed=JSON.parse(value) as unknown;return Array.isArray(parsed)?parsed:[];}catch{return[];}}
function parseObject(value:string):Record<string,unknown>{try{const parsed=JSON.parse(value) as unknown;return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed as Record<string,unknown>:{};}catch{return{};}}
function assertable(funnel:'CLIENT'|'JOB',from:string,to:string){try{assertTransition(funnel,from,to);return true;}catch{return false;}}
function withRates(data:Record<string,number>,steps:string[]){const base=Math.max(1,Number(data.discovered??0));return {...data,rates:Object.fromEntries(steps.map((key)=>[`${key}Rate`,Number(data[key]??0)/base]))};}
