import fs from 'node:fs';
import { describe,expect,it } from 'vitest';
import { academicSearchFiltersSchema,defaultAcademicSearchFilters } from '@gtm/academic';
import { AcademicRepository } from '@gtm/db';
import { createMigratedTestDatabase } from './db-helper';

describe('personal academic workspace',()=>{
  it('uses Abdul profile defaults and keeps the manuscript explicitly unpublished',()=>{const connection=createMigratedTestDatabase(),repo=new AcademicRepository(connection);const profile=repo.ensureDefaultProfile();expect(profile.name).toBe('Abdul Rehman');expect(profile.primaryInterests).toEqual(expect.arrayContaining(['Artificial Intelligence','Computer Science','Robotics + AI']));expect(profile.manuscripts).toEqual(expect.arrayContaining([expect.objectContaining({status:'MANUSCRIPT'})]));expect(defaultAcademicSearchFilters).toMatchObject({countries:['United States','Germany'],degree:'PHD',funding:'FULLY_FUNDED'});connection.sqlite.close();});
  it('validates multi-country, degree, funding, areas, clear, and personal-default filters',()=>{expect(academicSearchFiltersSchema.parse({countries:['United States','Germany','Canada'],degree:'MS_MSC',funding:'TUITION_FREE',researchAreas:['AI Memory','NLP'],keyword:'agents'})).toMatchObject({countries:['United States','Germany','Canada'],degree:'MS_MSC',funding:'TUITION_FREE',researchAreas:['AI Memory','NLP']});const clear=academicSearchFiltersSchema.parse({countries:[],degree:'ANY',funding:'ANY',researchAreas:[],keyword:'',status:'ALL'});expect(clear).toMatchObject({countries:[],degree:'ANY',funding:'ANY',researchAreas:[]});});
  it('persists searches, queues background research, filters results, and restores history',()=>{const connection=createMigratedTestDatabase(),repo=new AcademicRepository(connection);const us=repo.upsertUniversity({name:'US Research University',country:'United States'}),de=repo.upsertUniversity({name:'German Research University',country:'Germany'});repo.createOpportunity({universityId:us.id,title:'AI Memory PhD',degreeLevel:'PHD',country:'United States',fundingCategory:'CONFIRMED_FULL_FUNDING'});repo.createOpportunity({universityId:de.id,title:'Robotics MSc',degreeLevel:'MASTERS',country:'Germany',fundingCategory:'TUITION_FREE_FUNDING_REQUIRED'});const filters=academicSearchFiltersSchema.parse({countries:['United States'],degree:'PHD',funding:'FULLY_FUNDED',researchAreas:['AI Memory']});const created=repo.createAcademicSearch(filters);expect((created.job as {type:string}).type).toBe('RUN_ACADEMIC_SEARCH');expect(repo.filterOpportunities(filters)).toHaveLength(1);expect(repo.listAcademicSearches()[0]?.filters).toEqual(filters);expect(repo.getSearchPreferences()).toEqual(filters);connection.sqlite.close();});
  it('completes deterministic searches while source refresh continues in the background',()=>{const connection=createMigratedTestDatabase(),repo=new AcademicRepository(connection);repo.saveSource({kind:'OFFICIAL_PROGRAM',name:'Example University',url:'https://example.edu/program',canonicalUrl:'https://example.edu/program',official:true});const created=repo.createAcademicSearch(academicSearchFiltersSchema.parse({countries:['Germany'],degree:'MS_MSC',funding:'FULLY_FUNDED',researchAreas:['AI']}));const result=repo.runAcademicSearch(created.search.id);expect(result).toMatchObject({status:'COMPLETED',sourcesQueued:1});expect(repo.getAcademicSearch(created.search.id)).toMatchObject({status:'COMPLETED'});connection.sqlite.close();});
  it('saves opportunities to a personal shortlist without altering application data',()=>{const connection=createMigratedTestDatabase(),repo=new AcademicRepository(connection);const university=repo.upsertUniversity({name:'Shortlist University',country:'Canada'}),opportunity=repo.createOpportunity({universityId:university.id,title:'Funded AI PhD',degreeLevel:'PHD',country:'Canada'});repo.saveToShortlist('OPPORTUNITY',opportunity.id);repo.saveToShortlist('OPPORTUNITY',opportunity.id);expect(repo.listShortlist()).toHaveLength(1);expect(repo.getApplicationCase(opportunity.id)?.status).toBe('DISCOVERED');repo.removeFromShortlist('OPPORTUNITY',opportunity.id);expect(repo.listShortlist()).toHaveLength(0);connection.sqlite.close();});
  it('always includes the current applicant profile in opportunity and professor AI context',()=>{const connection=createMigratedTestDatabase(),repo=new AcademicRepository(connection);const university=repo.upsertUniversity({name:'Context University',country:'Germany'}),opportunity=repo.createOpportunity({universityId:university.id,title:'LLM PhD',degreeLevel:'PHD',country:'Germany'}),professor=repo.upsertProfessor({universityId:university.id,fullName:'Professor Context'}),professorCase=repo.createProfessorCase({professorId:professor.id,opportunityId:opportunity.id})!;expect(repo.getOpportunityAiContext(opportunity.id).applicant.name).toBe('Abdul Rehman');expect(repo.getProfessorAiContext(professorCase.id).applicant.manuscripts[0]).toMatchObject({status:'MANUSCRIPT'});connection.sqlite.close();});
  it('makes Academic Intelligence the visible default and gives search requests visible feedback',()=>{const source=fs.readFileSync('apps/web/src/App.tsx','utf8');expect(source).toContain("useState('Home')");expect(source).toContain("['Search Opportunities',Search]");expect(source).toContain('Clear Filters');expect(source).toContain('Reset to My Defaults');expect(source).toContain('Search request saved.');expect(source).toContain('Search completed — no results found');expect(source).toContain('Research could not start.');expect(source).toContain('refetchInterval:5000');expect(source).not.toContain("['Client leads'");expect(source).not.toContain("['Jobs'");});
});
