import { describe,expect,it } from 'vitest';
import { AcademicRepository } from '@gtm/db';
import { createMigratedTestDatabase } from './db-helper';

describe('academic repository',()=>{
  it('seeds Abdul without claiming manuscript publication and deduplicates universities/professors',()=>{const connection=createMigratedTestDatabase(),repo=new AcademicRepository(connection);const profile=repo.ensureDefaultProfile();expect(profile.name).toBe('Abdul Rehman');expect((profile.manuscripts as Array<{status:string}>)[0]?.status).toBe('MANUSCRIPT');const u1=repo.upsertUniversity({name:'Technical University of Example',country:'Germany'}),u2=repo.upsertUniversity({name:'Technical University of Example',country:'Germany',city:'Berlin'});expect(u2.id).toBe(u1.id);const p1=repo.upsertProfessor({universityId:u1.id,fullName:'Ada Lovelace'}),p2=repo.upsertProfessor({universityId:u1.id,fullName:'Ada  Lovelace',researchAreas:['AI']});expect(p2.id).toBe(p1.id);connection.sqlite.close();});
  it('preserves source evidence, score snapshots, eligibility, and application history',()=>{const connection=createMigratedTestDatabase(),repo=new AcademicRepository(connection);const university=repo.upsertUniversity({name:'Example University',country:'United States'});const opportunity=repo.createOpportunity({universityId:university.id,title:'AI PhD',degreeLevel:'PHD',country:'United States',fundingCategory:'CONFIRMED_FULL_FUNDING'});const source=repo.saveSource({kind:'MANUAL_URL',name:'Official',url:'https://example.edu/phd',canonicalUrl:'https://example.edu/phd',official:true});const evidence=repo.saveEvidence({sourceId:source.id,entityType:'OPPORTUNITY',entityId:String(opportunity.id),claimType:'FUNDING',claim:'Tuition and stipend provided',sourceUrl:source.url,confidence:1});const eligible=repo.runEligibility(String(opportunity.id),[{key:'degree',result:'PASS',reason:'Relevant BS accepted',evidenceIds:[evidence.id]}]);expect(eligible.status).toBe('ELIGIBLE');const score=repo.scoreOpportunity(String(opportunity.id),{funding:'CONFIRMED_FULL_FUNDING',eligibility:'ELIGIBLE',researchMatch:1,professorMatch:.8,programQuality:.8,directSupervisor:true,deadlineFreshness:1,feasibility:.8,contactability:.8,evidenceCompleteness:1,evidenceIds:[evidence.id]});expect(score.total).toBeGreaterThan(80);repo.updateApplicationStatus(String(opportunity.id),'RESEARCHING');expect(connection.sqlite.prepare(`SELECT count(*) count FROM activities WHERE entity_type='ACADEMIC_APPLICATION'`).get()).toMatchObject({count:1});connection.sqlite.close();});
  it('requires approval and prevents duplicate send queue entries',()=>{const connection=createMigratedTestDatabase(),repo=new AcademicRepository(connection);const university=repo.upsertUniversity({name:'Case University',country:'Germany'});const professor=repo.upsertProfessor({universityId:university.id,fullName:'Professor Test',publicEmail:'test@example.edu'});const professorCase=repo.createProfessorCase({professorId:professor.id});const draft=repo.saveOutreachDraft({professorCaseId:professorCase!.id,recipientEmail:'test@example.edu',subjects:['Research inquiry'],textBody:'Evidence-backed message',idempotencyKey:'case-unique-1'});expect(()=>repo.queueOutreach(draft.id)).toThrow(/approved/);repo.approveOutreach(draft.id);const first=repo.queueOutreach(draft.id) as {id:string};const second=repo.queueOutreach(draft.id) as {id:string};expect(second.id).toBe(first.id);connection.sqlite.close();});
});
