import { describe, expect, it, vi } from 'vitest';
import { AIProviderError, browserDiscoverWithRetry, companyAnalysisSchema, createAIProvider, GroqProvider, OllamaProvider, ResilientAIProvider, type AIProvider } from '@gtm/ai';
import { loadConfig } from '@gtm/shared';
import { z } from 'zod';

const valid = { companySummary: 'Acme provides an AI support product.', industry: 'Software', businessModel: 'SaaS', companyStage: null, products: ['Support assistant'], customerTypes: ['Support teams'], technicalFocus: ['LLM'], aiRelevance: .9, engineeringNeed: .7, buyingIntent: .6, possiblePainPoints: [{ text: 'May need delivery capacity', classification: 'HYPOTHESIS', confidence: .6, evidenceIds: [] }], recommendedServices: [], signals: [], risks: [], confidence: .8 };

describe('Ollama provider', () => {
  it('reports configured model availability', async () => {
    const fetcher = vi.fn().mockResolvedValue(new Response(JSON.stringify({ models: [{ name: 'qwen2.5:7b' }] }), { status: 200 }));
    await expect(new OllamaProvider('http://localhost:11434', 'qwen2.5:7b', fetcher).healthCheck()).resolves.toMatchObject({ status: 'available' });
  });
  it('validates structured output with Zod', async () => {
    const fetcher = vi.fn().mockResolvedValue(new Response(JSON.stringify({ message: { content: JSON.stringify(valid) }, prompt_eval_count: 10, eval_count: 20 }), { status: 200 }));
    const result = await new OllamaProvider('http://localhost:11434', 'qwen2.5:7b', fetcher).generateStructured({ system: 'grounded', prompt: '{}', schema: companyAnalysisSchema, schemaName: 'company' });
    expect(result.data.confidence).toBe(.8); expect(result.promptTokens).toBe(10);
  });
  it('rejects invalid model output rather than trusting it', async () => {
    const fetcher = vi.fn().mockResolvedValue(new Response(JSON.stringify({ message: { content: '{"companySummary":42}' } }), { status: 200 }));
    await expect(new OllamaProvider('http://localhost:11434', 'qwen2.5:7b', fetcher).generateStructured({ system: 'grounded', prompt: '{}', schema: companyAnalysisSchema, schemaName: 'company' })).rejects.toThrow();
  });
});

describe('Groq and provider selection',()=>{
  const schema=z.object({answer:z.string()});
  it('parses a structured response and token metadata without exposing credentials',async()=>{const fetcher=async()=>new Response(JSON.stringify({model:'openai/gpt-oss-120b',choices:[{message:{content:'{"answer":"grounded"}'}}],usage:{prompt_tokens:12,completion_tokens:4}}),{status:200,headers:{'content-type':'application/json'}});const result=await new GroqProvider('https://api.groq.com/openai/v1','openai/gpt-oss-120b','secret-value',1000,fetcher as typeof fetch).generateStructured({system:'safe',prompt:'bounded',schema,schemaName:'answer'});expect(result).toMatchObject({provider:'groq',model:'openai/gpt-oss-120b',data:{answer:'grounded'},promptTokens:12,completionTokens:4});expect(JSON.stringify(result)).not.toContain('secret-value');});
  it('parses browser-search leads while enabling the Groq browser tool',async()=>{let body='';const fetcher=async(_url:URL|string,init?:RequestInit)=>{body=String(init?.body);return new Response(JSON.stringify({model:'openai/gpt-oss-120b',choices:[{message:{content:'```json\n{"answer":"official lead"}\n```'}}],usage:{prompt_tokens:20,completion_tokens:5}}),{status:200});};const result=await new GroqProvider('https://api.groq.com/openai/v1','openai/gpt-oss-120b','key',1000,fetcher as typeof fetch).browserSearchStructured({prompt:'find official sources',schema});expect(result.data).toEqual({answer:'official lead'});expect(JSON.parse(body)).toMatchObject({tool_choice:'required',tools:[{type:'browser_search'}]});});
  it('uses provider search metadata as candidate leads instead of parsing final prose as facts',async()=>{const fetcher=async()=>new Response(JSON.stringify({model:'model',choices:[{message:{content:'Possible source',executed_tools:[{search_results:{results:[{url:'https://example.edu/phd',title:'AI PhD',snippet:'Official program'}]}}]}}]}),{status:200});const result=await new GroqProvider('https://api.groq.com/openai/v1','model','key',1000,fetcher as typeof fetch).browserDiscover({query:'AI PhD',maxResults:3});expect(result.results).toEqual([{url:'https://example.edu/phd',title:'AI PhD',snippet:'Official program'}]);});
  it('uses independently validated normal and browser timeout configuration',()=>{const config=loadConfig({AI_REQUEST_TIMEOUT_MS:'12000',GROQ_BROWSER_SEARCH_TIMEOUT_MS:'90000'} as NodeJS.ProcessEnv);expect(config.AI_REQUEST_TIMEOUT_MS).toBe(12000);expect(config.GROQ_BROWSER_SEARCH_TIMEOUT_MS).toBe(90000);expect(loadConfig({} as NodeJS.ProcessEnv).GROQ_BROWSER_SEARCH_TIMEOUT_MS).toBe(90000);expect(()=>loadConfig({GROQ_BROWSER_SEARCH_TIMEOUT_MS:'0'} as NodeJS.ProcessEnv)).toThrow();});
  it('retries browser discovery once after timeout and records both attempts',async()=>{let calls=0;const fetcher=async()=>{calls++;if(calls===1)throw new DOMException('timed out','TimeoutError');return new Response(JSON.stringify({model:'model',search_results:[{url:'https://example.edu/phd',title:'AI PhD',snippet:'Official'}]}),{status:200})};const result=await browserDiscoverWithRetry(new GroqProvider('https://api.groq.com/openai/v1','model','key',50,fetcher as typeof fetch),{query:'AI PhD'},{sleep:async()=>undefined});expect(calls).toBe(2);expect(result.diagnostics).toMatchObject([{attempt:1,failureCategory:'TIMEOUT',resultCount:0},{attempt:2,failureCategory:null,resultCount:1}]);});
  it('stops after the second transient failure but never retries auth',async()=>{let timeoutCalls=0;const timeout=async()=>{timeoutCalls++;throw new DOMException('timed out','TimeoutError')};await expect(browserDiscoverWithRetry(new GroqProvider('https://api.groq.com/openai/v1','model','key',5,timeout as typeof fetch),{query:'AI'},{sleep:async()=>undefined})).rejects.toMatchObject({code:'TIMEOUT',diagnostics:[{attempt:1},{attempt:2}]});expect(timeoutCalls).toBe(2);let authCalls=0;const auth=async()=>{authCalls++;return new Response('{}',{status:401})};await expect(browserDiscoverWithRetry(new GroqProvider('https://api.groq.com/openai/v1','model','key',5,auth as typeof fetch),{query:'AI'},{sleep:async()=>undefined})).rejects.toMatchObject({code:'AUTH',diagnostics:[{attempt:1}]});expect(authCalls).toBe(1);});
  it('bounds rate-limit retry metadata safely',async()=>{let calls=0;const delays:number[]=[];const limited=async()=>{calls++;return new Response('{}',{status:429,headers:{'retry-after':'60'}})};await expect(browserDiscoverWithRetry(new GroqProvider('https://api.groq.com/openai/v1','model','key',5,limited as typeof fetch),{query:'AI'},{sleep:async ms=>{delays.push(ms)},maxBackoffMs:2000})).rejects.toMatchObject({code:'RATE_LIMITED'});expect(calls).toBe(2);expect(delays).toEqual([2000]);});
  it('rejects malformed JSON and schema-invalid JSON',async()=>{const malformed=async()=>new Response(JSON.stringify({choices:[{message:{content:'not-json'}}]}),{status:200});await expect(new GroqProvider('https://api.groq.com/openai/v1','model','key',1000,malformed as typeof fetch).generateStructured({system:'x',prompt:'x',schema,schemaName:'test'})).rejects.toMatchObject({code:'INVALID_RESPONSE'});const invalid=async()=>new Response(JSON.stringify({choices:[{message:{content:'{"wrong":true}'}}]}),{status:200});await expect(new GroqProvider('https://api.groq.com/openai/v1','model','key',1000,invalid as typeof fetch).generateStructured({system:'x',prompt:'x',schema,schemaName:'test'})).rejects.toThrow();});
  it('reports missing keys and classifies auth, rate-limit, and timeout failures',async()=>{const missing=new GroqProvider('https://api.groq.com/openai/v1','model',undefined);expect(await missing.healthCheck()).toMatchObject({status:'misconfigured'});await expect(missing.generateStructured({system:'x',prompt:'x',schema,schemaName:'test'})).rejects.toMatchObject({code:'MISCONFIGURED'});for(const status of [401,403]){const fetcher=async()=>new Response('{}',{status});await expect(new GroqProvider('https://api.groq.com/openai/v1','model','key',1000,fetcher as typeof fetch).generateStructured({system:'x',prompt:'x',schema,schemaName:'test'})).rejects.toMatchObject({code:'AUTH'});}const limited=async()=>new Response('{}',{status:429,headers:{'retry-after':'2'}});await expect(new GroqProvider('https://api.groq.com/openai/v1','model','key',1000,limited as typeof fetch).generateStructured({system:'x',prompt:'x',schema,schemaName:'test'})).rejects.toMatchObject({code:'RATE_LIMITED',retryAfterMs:2000});const timeout=async()=>{throw new DOMException('timed out','TimeoutError')};await expect(new GroqProvider('https://api.groq.com/openai/v1','model','key',1,timeout as typeof fetch).generateStructured({system:'x',prompt:'x',schema,schemaName:'test'})).rejects.toMatchObject({code:'TIMEOUT'});});
  it('selects explicit modes and falls from Groq to Ollama in auto mode',async()=>{const fetcher=async(url:URL|string)=>{const value=String(url);if(value.includes('api.groq.com'))return new Response('{}',{status:429});if(value.endsWith('/api/tags'))return new Response(JSON.stringify({models:[{name:'qwen2.5:7b'}]}),{status:200});return new Response(JSON.stringify({message:{content:'{"answer":"local"}'},prompt_eval_count:3,eval_count:2}),{status:200});};const config={AI_PROVIDER:'auto' as const,GROQ_API_KEY:'key',GROQ_BASE_URL:'https://api.groq.com/openai/v1',GROQ_MODEL:'openai/gpt-oss-120b',OLLAMA_BASE_URL:'http://localhost:11434',OLLAMA_MODEL:'qwen2.5:7b'};const auto=createAIProvider(config,{fetcher:fetcher as typeof fetch});expect(auto).toBeInstanceOf(ResilientAIProvider);await expect(auto.generateStructured({system:'x',prompt:'x',schema,schemaName:'test'})).resolves.toMatchObject({provider:'ollama',data:{answer:'local'}});expect(createAIProvider({...config,AI_PROVIDER:'groq'}).name).toBe('groq');expect(createAIProvider({...config,AI_PROVIDER:'ollama'}).name).toBe('ollama');expect(createAIProvider({...config,AI_PROVIDER:'none'}).name).toBe('none');});
  it('fails once all providers are unavailable so deterministic callers can continue',async()=>{const unavailable=(name:string):AIProvider=>({name,modelInfo:()=>({provider:name,model:'none',baseUrl:'local'}),healthCheck:async()=>({status:'unavailable',provider:name,model:'none'}),generateStructured:async()=>{throw new AIProviderError('unavailable','UPSTREAM',name)}});const provider=new ResilientAIProvider([unavailable('groq'),unavailable('ollama')]);await expect(provider.generateStructured({system:'x',prompt:'x',schema,schemaName:'test'})).rejects.toMatchObject({provider:'none'});});
});
