import { describe, expect, it } from 'vitest';
import { assertSendAllowed, buildOutreachStrategy, classifyReplyDeterministically, followupDates, groundedApplicationFallback, groundedOutreachFallback, isHighIntent, matchCandidate, matchService, normalizeSubject, threadMatch } from '@gtm/operations';

describe('operational GTM rules',()=>{
  it('selects one evidence-backed primary service',()=>{const result=matchService([{id:'e1',type:'LLM_ENGINEER_HIRING',claim:'Hiring a senior LLM engineer',confidence:.98}]);expect(result.primarySlug).toBe('llm-engineering');expect(result.evidenceIds).toContain('e1');});
  it('builds a specific strategy and grounded message',()=>{const strategy=buildOutreachStrategy({opportunityId:'o',companyId:'c',personId:'p',serviceName:'LLM Engineering',serviceMatchId:'s',signals:[{type:'LLM_ENGINEER_HIRING',confidence:.95}],evidenceHash:'h'});const message=groundedOutreachFallback({firstName:'Sam',companyName:'Acme',evidenceClaim:'Acme is hiring an LLM engineer',serviceName:'LLM Engineering',angle:strategy.angle,cta:strategy.cta});expect(message.coldEmail).toContain('hiring an LLM engineer');expect(message.followups).toHaveLength(3);});
  it('enforces approval, suppression, confidence, inference and idempotency',()=>{const valid={status:'APPROVED',suppressed:false,unsubscribed:false,permanentlyBounced:false,contactConfidence:95,minimumConfidence:75,inferred:false,inferredConfirmed:false,sentCountHour:0,sentCountDay:0,hourlyLimit:10,dailyLimit:40,alreadySent:false};expect(()=>assertSendAllowed(valid)).not.toThrow();expect(()=>assertSendAllowed({...valid,status:'DRAFT'})).toThrow(/approved/);expect(()=>assertSendAllowed({...valid,suppressed:true})).toThrow(/suppressed/);expect(()=>assertSendAllowed({...valid,inferred:true})).toThrow(/explicit/);expect(()=>assertSendAllowed({...valid,alreadySent:true})).toThrow(/already sent/);});
  it('schedules followups at stable offsets',()=>{const dates=followupDates(new Date('2026-01-01T00:00:00.000Z'));expect(dates).toEqual(['2026-01-05T00:00:00.000Z','2026-01-10T00:00:00.000Z','2026-01-17T00:00:00.000Z']);});
  it('matches threads by headers before subject fallback',()=>{const candidates=[{id:'a',messageIds:['<one>'],contact:'x@acme.com',normalizedSubject:'hello'}];expect(threadMatch({inReplyTo:'<one>',sender:'other@acme.com',subject:'different'},candidates)?.id).toBe('a');expect(normalizeSubject('Re: Fwd: Hello')).toBe('hello');});
  it('classifies explicit replies and identifies high intent',()=>{expect(classifyReplyDeterministically('Please remove me').classification).toBe('UNSUBSCRIBE');const interested=classifyReplyDeterministically('Can we schedule a call?');expect(interested.classification).toBe('INTERESTED');expect(isHighIntent(interested.classification)).toBe(true);});
  it('never invents candidate skills in application material',()=>{const candidate={summary:'Full-stack engineer.',skills:['TypeScript','React'],technologies:['Node.js'],experience:[],projects:[{id:'p1',name:'Portal',description:'A portal',technologies:['React']}]};const match=matchCandidate(candidate,{title:'Full-Stack Engineer',description:'React, TypeScript, Python',location:'Remote'});const packageDraft=groundedApplicationFallback(candidate,{title:'Full-Stack Engineer',companyName:'Acme'},match);expect(match.strongSkills).toEqual(expect.arrayContaining(['TypeScript','React']));expect(match.missingSkills).toContain('python');expect(packageDraft.coverLetter.toLowerCase()).not.toContain('years');});
});
