import { describe,expect,it,vi } from 'vitest';
import { generateAcademicDiscoveryQueries,isLikelyOfficialAcademicUrl,normalizeAcademicUrl,TavilyDiscoveryError,TavilyDiscoveryProvider } from '@gtm/academic';

const provider=(fetchImpl:typeof fetch,apiKey='secret')=>new TavilyDiscoveryProvider({apiKey,baseUrl:'https://api.tavily.com',searchDepth:'basic',timeoutMs:20,fetchImpl});
describe('Tavily academic discovery',()=>{
  it('returns candidates without requesting an answer or exposing the key',async()=>{const mock=vi.fn(async(_url:unknown,init?:RequestInit)=>{const body=JSON.parse(String(init?.body));expect(body).toMatchObject({api_key:'secret',include_answer:false,include_raw_content:false});return new Response(JSON.stringify({results:[{url:'http://www.example.edu/phd?utm_source=x#funding',title:'AI PhD',content:'Funding signal',score:.9}]}),{status:200});}) as unknown as typeof fetch;const results=await provider(mock).search('site:.edu AI PhD',8);expect(results[0]).toMatchObject({url:'https://example.edu/phd',provider:'TAVILY_DISCOVERY',snippet:'Funding signal',score:.9});});
  it('reports a missing key safely',async()=>{await expect(new TavilyDiscoveryProvider({baseUrl:'https://api.tavily.com',searchDepth:'basic',timeoutMs:20}).search('x',1)).rejects.toMatchObject({category:'MISCONFIGURED'});});
  it.each([[401,'AUTH'],[429,'RATE_LIMITED'],[500,'UPSTREAM']] as const)('maps status %s to %s',async(status,category)=>{const mock=vi.fn(async()=>new Response('{}',{status})) as unknown as typeof fetch;await expect(provider(mock).search('x',1)).rejects.toMatchObject({category});});
  it('rejects malformed responses',async()=>{const mock=vi.fn(async()=>new Response(JSON.stringify({answer:'not results'}),{status:200})) as unknown as typeof fetch;await expect(provider(mock).search('x',1)).rejects.toMatchObject({category:'MALFORMED_RESPONSE'});});
  it('times out bounded requests',async()=>{const mock=vi.fn(async(_url:unknown,init?:RequestInit)=>new Promise<Response>((_resolve,reject)=>init?.signal?.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError'))))) as unknown as typeof fetch;await expect(provider(mock).search('x',1)).rejects.toBeInstanceOf(TavilyDiscoveryError);await expect(provider(mock).search('x',1)).rejects.toMatchObject({category:'TIMEOUT'});});
  it('normalizes duplicates and recognizes official hosts',()=>{expect(normalizeAcademicUrl('http://www.mit.edu/a/?utm_campaign=x#b')).toBe('https://mit.edu/a');expect(isLikelyOfficialAcademicUrl('https://cs.mit.edu/phd',['United States'])).toBe(true);expect(isLikelyOfficialAcademicUrl('https://findaphd.com/x',['United States'])).toBe(false);});
  it('builds bounded targeted queries without applicant details',()=>{const queries=generateAcademicDiscoveryQueries({countries:['United States'],degree:'PHD',funding:'FULLY_FUNDED',researchAreas:['Artificial Intelligence','LLMs','AI Memory','AI Agents'],keyword:'',status:'ALL',sort:'BEST_MATCH'},6);expect(queries.length).toBeGreaterThanOrEqual(4);expect(queries.length).toBeLessThanOrEqual(6);expect(queries.every(q=>q.includes('site:.edu'))).toBe(true);expect(queries.join(' ')).not.toContain('Abdul');});
});
