import type { z } from 'zod';
import { AIProviderError, type AIHealth, type AIProvider, type StructuredGeneration } from './types.js';

export class GroqProvider implements AIProvider{
  readonly name='groq';
  constructor(private readonly baseUrl:string,private readonly model:string,private readonly apiKey:string|undefined,private readonly timeoutMs=60_000,private readonly fetcher:typeof fetch=fetch){}
  modelInfo(){return{provider:this.name,model:this.model,baseUrl:this.baseUrl};}
  async healthCheck():Promise<AIHealth>{if(!this.apiKey)return{status:'misconfigured',provider:this.name,model:this.model,detail:'GROQ_API_KEY is not configured'};try{const response=await this.fetcher(`${this.baseUrl.replace(/\/$/,'')}/models`,{headers:{authorization:`Bearer ${this.apiKey}`},signal:AbortSignal.timeout(Math.min(this.timeoutMs,5_000))});if(response.status===401||response.status===403)return{status:'misconfigured',provider:this.name,model:this.model,detail:'Groq authentication failed'};if(response.status===429)return{status:'unavailable',provider:this.name,model:this.model,detail:'Groq rate limit reached'};if(!response.ok)return{status:'unavailable',provider:this.name,model:this.model,detail:`Groq returned HTTP ${response.status}`};return{status:'available',provider:this.name,model:this.model};}catch(error){return{status:'unavailable',provider:this.name,model:this.model,detail:isTimeout(error)?'Groq health check timed out':'Groq is unreachable'};}}
  async generateStructured<T>(input:{system:string;prompt:string;schema:z.ZodType<T>;schemaName:string;temperature?:number}):Promise<StructuredGeneration<T>>{if(!this.apiKey)throw new AIProviderError('GROQ_API_KEY is not configured','MISCONFIGURED',this.name);const started=Date.now();let response:Response;try{response=await this.fetcher(`${this.baseUrl.replace(/\/$/,'')}/chat/completions`,{method:'POST',signal:AbortSignal.timeout(this.timeoutMs),headers:{authorization:`Bearer ${this.apiKey}`,'content-type':'application/json'},body:JSON.stringify({model:this.model,temperature:input.temperature??0.1,response_format:{type:'json_object'},messages:[{role:'system',content:`${input.system}\nReturn one JSON object matching the ${input.schemaName} schema. No markdown.`},{role:'user',content:input.prompt}]})});}catch(error){if(isTimeout(error))throw new AIProviderError('Groq request timed out','TIMEOUT',this.name);throw new AIProviderError('Groq request failed','UPSTREAM',this.name);}
    if(response.status===401||response.status===403)throw new AIProviderError('Groq authentication failed','AUTH',this.name);if(response.status===429){const retryAfterMs=parseRetryAfter(response.headers.get('retry-after'));throw new AIProviderError('Groq rate limit reached','RATE_LIMITED',this.name,retryAfterMs);}if(!response.ok)throw new AIProviderError(`Groq returned HTTP ${response.status}`,'UPSTREAM',this.name);
    let raw:GroqResponse;try{raw=await response.json() as GroqResponse;}catch{throw new AIProviderError('Groq returned malformed JSON','INVALID_RESPONSE',this.name);}const content=raw.choices?.[0]?.message?.content;if(!content)throw new AIProviderError(`Groq returned no structured content for ${input.schemaName}`,'INVALID_RESPONSE',this.name);let value:unknown;try{value=JSON.parse(content);}catch{throw new AIProviderError(`Groq returned invalid JSON for ${input.schemaName}`,'INVALID_RESPONSE',this.name);}return{data:input.schema.parse(value),raw,model:raw.model||this.model,provider:this.name,latencyMs:Date.now()-started,promptTokens:raw.usage?.prompt_tokens??null,completionTokens:raw.usage?.completion_tokens??null};}
}
type GroqResponse={model?:string;choices?:Array<{message?:{content?:string}}> ;usage?:{prompt_tokens?:number;completion_tokens?:number}};
const isTimeout=(error:unknown)=>error instanceof Error&&(error.name==='TimeoutError'||error.name==='AbortError');
function parseRetryAfter(value:string|null){if(!value)return undefined;const seconds=Number(value);if(Number.isFinite(seconds)&&seconds>=0)return seconds*1000;const date=Date.parse(value);return Number.isFinite(date)?Math.max(0,date-Date.now()):undefined;}
