import type { z } from 'zod';
import { AIProviderError, type AIHealth, type AIProvider, type StructuredGeneration } from './types.js';

export type BrowserDiscoveryDiagnostic={provider:string;model:string;attempt:number;durationMs:number;resultCount:number;failureCategory:string|null;fallbackUsed:boolean};
export async function browserDiscoverWithRetry(provider:GroqProvider,input:{query:string;maxResults?:number},options:{onAttempt?:(diagnostic:BrowserDiscoveryDiagnostic)=>void|Promise<void>;sleep?:(ms:number)=>Promise<void>;maxBackoffMs?:number}={}){
  const diagnostics:BrowserDiscoveryDiagnostic[]=[];const sleep=options.sleep??(ms=>new Promise(resolve=>setTimeout(resolve,ms)));const maxBackoff=options.maxBackoffMs??3_000;
  for(let attempt=1;attempt<=2;attempt++){const started=Date.now();try{const result=await provider.browserDiscover(input);const diagnostic={provider:result.provider,model:result.model,attempt,durationMs:result.latencyMs,resultCount:result.results.length,failureCategory:null,fallbackUsed:false};diagnostics.push(diagnostic);await options.onAttempt?.(diagnostic);return{...result,diagnostics}}catch(error){const failure=error instanceof AIProviderError?error:new AIProviderError('Groq browser discovery failed','UPSTREAM','groq');const diagnostic={provider:failure.provider,model:provider.modelInfo().model,attempt,durationMs:Date.now()-started,resultCount:0,failureCategory:failure.code==='MISCONFIGURED'?'AUTH':failure.code,fallbackUsed:false};diagnostics.push(diagnostic);await options.onAttempt?.(diagnostic);const retryable=['TIMEOUT','UPSTREAM','RATE_LIMITED'].includes(failure.code);if(attempt===2||!retryable){Object.assign(failure,{diagnostics});throw failure}const requested=failure.code==='RATE_LIMITED'?(failure.retryAfterMs??500):500;await sleep(Math.min(maxBackoff,Math.max(100,requested)));}}
  throw new AIProviderError('Groq browser discovery failed','UPSTREAM','groq');
}

export class GroqProvider implements AIProvider{
  readonly name='groq';
  constructor(private readonly baseUrl:string,private readonly model:string,private readonly apiKey:string|undefined,private readonly timeoutMs=60_000,private readonly fetcher:typeof fetch=fetch){}
  modelInfo(){return{provider:this.name,model:this.model,baseUrl:this.baseUrl};}
  async healthCheck():Promise<AIHealth>{if(!this.apiKey)return{status:'misconfigured',provider:this.name,model:this.model,detail:'GROQ_API_KEY is not configured'};try{const response=await this.fetcher(`${this.baseUrl.replace(/\/$/,'')}/models`,{headers:{authorization:`Bearer ${this.apiKey}`},signal:AbortSignal.timeout(Math.min(this.timeoutMs,5_000))});if(response.status===401||response.status===403)return{status:'misconfigured',provider:this.name,model:this.model,detail:'Groq authentication failed'};if(response.status===429)return{status:'unavailable',provider:this.name,model:this.model,detail:'Groq rate limit reached'};if(!response.ok)return{status:'unavailable',provider:this.name,model:this.model,detail:`Groq returned HTTP ${response.status}`};return{status:'available',provider:this.name,model:this.model};}catch(error){return{status:'unavailable',provider:this.name,model:this.model,detail:isTimeout(error)?'Groq health check timed out':'Groq is unreachable'};}}
  async generateStructured<T>(input:{system:string;prompt:string;schema:z.ZodType<T>;schemaName:string;temperature?:number}):Promise<StructuredGeneration<T>>{if(!this.apiKey)throw new AIProviderError('GROQ_API_KEY is not configured','MISCONFIGURED',this.name);const started=Date.now();let response:Response;try{response=await this.fetcher(`${this.baseUrl.replace(/\/$/,'')}/chat/completions`,{method:'POST',signal:AbortSignal.timeout(this.timeoutMs),headers:{authorization:`Bearer ${this.apiKey}`,'content-type':'application/json'},body:JSON.stringify({model:this.model,temperature:input.temperature??0.1,response_format:{type:'json_object'},messages:[{role:'system',content:`${input.system}\nReturn one JSON object matching the ${input.schemaName} schema. No markdown.`},{role:'user',content:input.prompt}]})});}catch(error){if(isTimeout(error))throw new AIProviderError('Groq request timed out','TIMEOUT',this.name);throw new AIProviderError('Groq request failed','UPSTREAM',this.name);}
    if(response.status===401||response.status===403)throw new AIProviderError('Groq authentication failed','AUTH',this.name);if(response.status===429){const retryAfterMs=parseRetryAfter(response.headers.get('retry-after'));throw new AIProviderError('Groq rate limit reached','RATE_LIMITED',this.name,retryAfterMs);}if(!response.ok)throw new AIProviderError(`Groq returned HTTP ${response.status}`,'UPSTREAM',this.name);
    let raw:GroqResponse;try{raw=await response.json() as GroqResponse;}catch{throw new AIProviderError('Groq returned malformed JSON','INVALID_RESPONSE',this.name);}const content=raw.choices?.[0]?.message?.content;if(!content)throw new AIProviderError(`Groq returned no structured content for ${input.schemaName}`,'INVALID_RESPONSE',this.name);let value:unknown;try{value=JSON.parse(content);}catch{throw new AIProviderError(`Groq returned invalid JSON for ${input.schemaName}`,'INVALID_RESPONSE',this.name);}return{data:input.schema.parse(value),raw,model:raw.model||this.model,provider:this.name,latencyMs:Date.now()-started,promptTokens:raw.usage?.prompt_tokens??null,completionTokens:raw.usage?.completion_tokens??null};}
  async browserSearchStructured<T>(input:{prompt:string;schema:z.ZodType<T>}):Promise<StructuredGeneration<T>>{if(!this.apiKey)throw new AIProviderError('GROQ_API_KEY is not configured','MISCONFIGURED',this.name);const started=Date.now();let response:Response;try{response=await this.fetcher(`${this.baseUrl.replace(/\/$/,'')}/chat/completions`,{method:'POST',signal:AbortSignal.timeout(this.timeoutMs),headers:{authorization:`Bearer ${this.apiKey}`,'content-type':'application/json'},body:JSON.stringify({model:this.model,temperature:.1,tool_choice:'required',tools:[{type:'browser_search'}],messages:[{role:'system',content:'Discover current academic opportunities. Return only valid JSON, without markdown. Search results are leads only and will be independently verified.'},{role:'user',content:input.prompt}]})});}catch(error){if(isTimeout(error))throw new AIProviderError('Groq browser search timed out','TIMEOUT',this.name);throw new AIProviderError('Groq browser search failed','UPSTREAM',this.name);}if(response.status===401||response.status===403)throw new AIProviderError('Groq authentication failed','AUTH',this.name);if(response.status===429)throw new AIProviderError('Groq rate limit reached','RATE_LIMITED',this.name,parseRetryAfter(response.headers.get('retry-after')));if(!response.ok)throw new AIProviderError(`Groq browser search returned HTTP ${response.status}`,'UPSTREAM',this.name);const raw=await response.json() as GroqResponse;const content=raw.choices?.[0]?.message?.content;if(!content)throw new AIProviderError('Groq browser search returned no content','INVALID_RESPONSE',this.name);const json=extractJson(content);let value:unknown;try{value=JSON.parse(json);}catch{throw new AIProviderError('Groq browser search returned invalid JSON','INVALID_RESPONSE',this.name);}return{data:input.schema.parse(value),raw,model:raw.model||this.model,provider:this.name,latencyMs:Date.now()-started,promptTokens:raw.usage?.prompt_tokens??null,completionTokens:raw.usage?.completion_tokens??null};}
  async browserDiscover(input:{query:string;maxResults?:number}){if(!this.apiKey)throw new AIProviderError('GROQ_API_KEY is not configured','MISCONFIGURED',this.name);const started=Date.now();let response:Response;try{response=await this.fetcher(`${this.baseUrl.replace(/\/$/,'')}/chat/completions`,{method:'POST',signal:AbortSignal.timeout(this.timeoutMs),headers:{authorization:`Bearer ${this.apiKey}`,'content-type':'application/json'},body:JSON.stringify({model:this.model,temperature:.1,tool_choice:'required',tools:[{type:'browser_search'}],messages:[{role:'system',content:'Find official university, government scholarship, or research institute pages. Search results are candidate leads only; do not synthesize facts.'},{role:'user',content:input.query}]})});}catch(error){if(isTimeout(error))throw new AIProviderError('Groq browser search timed out','TIMEOUT',this.name);throw new AIProviderError('Groq browser search failed','UPSTREAM',this.name);}if(response.status===401||response.status===403)throw new AIProviderError('Groq authentication failed','AUTH',this.name);if(response.status===429)throw new AIProviderError('Groq rate limit reached','RATE_LIMITED',this.name,parseRetryAfter(response.headers.get('retry-after')));if(!response.ok)throw new AIProviderError(`Groq browser search returned HTTP ${response.status}`,'UPSTREAM',this.name);let raw:GroqResponse;try{raw=await response.json() as GroqResponse}catch{throw new AIProviderError('Groq browser search returned malformed response','INVALID_RESPONSE',this.name)}const results=extractSearchResults(raw).slice(0,input.maxResults??10);if(!results.length)throw new AIProviderError('Groq browser search returned no candidate URLs','INVALID_RESPONSE',this.name);return{results,raw,model:raw.model||this.model,provider:this.name,latencyMs:Date.now()-started,promptTokens:raw.usage?.prompt_tokens??null,completionTokens:raw.usage?.completion_tokens??null};}
}
type GroqResponse={model?:string;choices?:Array<{message?:{content?:string;executed_tools?:unknown;tool_calls?:unknown;citations?:unknown}}> ;usage?:{prompt_tokens?:number;completion_tokens?:number};citations?:unknown;search_results?:unknown};
const isTimeout=(error:unknown)=>error instanceof Error&&(error.name==='TimeoutError'||error.name==='AbortError');
function parseRetryAfter(value:string|null){if(!value)return undefined;const seconds=Number(value);if(Number.isFinite(seconds)&&seconds>=0)return seconds*1000;const date=Date.parse(value);return Number.isFinite(date)?Math.max(0,date-Date.now()):undefined;}
function extractJson(value:string){const fenced=value.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1];if(fenced)return fenced.trim();const start=value.indexOf('{'),end=value.lastIndexOf('}');return start>=0&&end>start?value.slice(start,end+1):value.trim();}
function extractSearchResults(raw:GroqResponse){const found=new Map<string,{url:string;title:string;snippet:string}>();const visit=(value:unknown)=>{if(Array.isArray(value)){value.forEach(visit);return}if(!value||typeof value!=='object')return;const row=value as Record<string,unknown>;const url=typeof row.url==='string'?row.url:typeof row.link==='string'?row.link:typeof row.source_url==='string'?row.source_url:null;if(url&&/^https?:\/\//.test(url))found.set(url,{url,title:String(row.title??row.name??new URL(url).hostname),snippet:String(row.snippet??row.description??row.text??'')});Object.values(row).forEach(visit)};visit(raw.search_results);visit(raw.citations);visit(raw.choices?.[0]?.message?.executed_tools);visit(raw.choices?.[0]?.message?.tool_calls);const content=raw.choices?.[0]?.message?.content??'';for(const match of content.matchAll(/https?:\/\/[^\s)\]}>"']+/g)){const url=match[0].replace(/[.,;]+$/,'');if(!found.has(url))found.set(url,{url,title:new URL(url).hostname,snippet:''})}return[...found.values()]}
